Repository ldtteam/minecolonies, pull requests merged in 2019-02, with the labels that each got.

#3391 multi dimensional colonies #2
  src/main/java/com/minecolonies/coremod/blocks/AbstractBlockHut.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowClipBoard.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowRequestDetail.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/commands/ActionArgumentType.java
  src/main/java/com/minecolonies/coremod/commands/CommandEntryPointNew.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/DeleteColonyCommand.java
  src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/event/ClientEventHandler.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/inventory/GuiHandler.java
  src/main/java/com/minecolonies/coremod/items/ItemScepterGuard.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewBuildingViewMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewCitizenViewMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveBuildingMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveCitizenMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveWorkOrderMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewWorkOrderMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/GuardMobAttackListMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/HappinessDataMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/PermissionsMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/TransferItemsToCitizenRequestMessage.java
  src/main/java/com/minecolonies/coremod/tileentities/ScarecrowTileEntity.java
  src/main/java/com/minecolonies/coremod/tileentities/TileEntityColonyBuilding.java
  src/test/java/com/minecolonies/coremod/commands/CommandEntryPointTest.java
Labels: in testing

#3383 Toggleable shepherd sheep autodyeing
  .gitignore
  src/api/java/com/minecolonies/api/colony/requestsystem/request/IRequest.java
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Tool.java
  src/api/java/com/minecolonies/api/util/NBTUtils.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/MineColonies.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowClipBoard.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutBaker.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCook.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCowboy.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutLumberjack.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutShepherd.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutStoneSmelter.java
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityCrafterMale.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/IColonyManagerCapability.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingCrafter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBarracks.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStoneSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingWareHouse.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobCombatTraining.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobStonemason.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/ResolverHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/StandardRequests.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractCraftingRequestResolver.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/factory/PrivateWorkerCraftingProductionResolverFactory.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/factory/PublicWorkerCraftingProductionResolverFactory.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/ClaimChunksCommand.java
  src/main/java/com/minecolonies/coremod/commands/generalcommands/BackupCommand.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkShepherd.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIStatePausedHandler.java
  src/main/java/com/minecolonies/coremod/entity/ai/mobs/AbstractEntityMinecoloniesMob.java
  src/main/java/com/minecolonies/coremod/entity/citizenhandlers/CitizenJobHandler.java
  src/main/java/com/minecolonies/coremod/fixers/EventBasedIdFixer.java
  src/main/java/com/minecolonies/coremod/network/messages/BlockParticleEffectMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/BuildToolPasteMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ColonyViewMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/ShepherdSetDyeSheepsMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/TeamColonyColorChangeMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/UpdateRequestStateMessage.java
  src/main/java/com/minecolonies/coremod/placementhandlers/MinecoloniesPlacementHandlers.java
  src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java
  src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java
  src/main/java/com/minecolonies/coremod/util/SortingUtils.java
  src/main/resources/assets/minecolonies/gui/windowhutshepherd.xml
  src/main/resources/assets/minecolonies/lang/en_us.lang
  src/test/java/com/minecolonies/coremod/commands/CommandEntryPointTest.java
Labels: ready for review

#3331 Children added to minecolonies
  src/api/java/com/minecolonies/api/colony/ColonyProgressType.java
  src/api/java/com/minecolonies/api/configuration/Configurations.java
  src/api/java/com/minecolonies/api/util/constant/CitizenConstants.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/MineColonies.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallHireCitizen.java
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityCitizenFemaleAristocrat.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/CitizenDataView.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractCitizenAssignable.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingHome.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/ProgressManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/interfaces/ICitizenManager.java
  src/main/java/com/minecolonies/coremod/commands/citizencommands/SpawnCitizenCommand.java
  src/main/java/com/minecolonies/coremod/entity/AbstractEntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenChild.java
  src/main/java/com/minecolonies/coremod/entity/ai/statemachine/AITarget.java
  src/main/java/com/minecolonies/coremod/entity/ai/statemachine/tickratestatemachine/TickRateStateMachine.java
  src/main/java/com/minecolonies/coremod/entity/citizenhandlers/CitizenColonyHandler.java
  src/main/java/com/minecolonies/coremod/entity/citizenhandlers/CitizenHappinessHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/BuyCitizenMessage.java
  src/main/java/com/minecolonies/coremod/sounds/ChildrenSounds.java
  src/main/java/com/minecolonies/coremod/sounds/ModSoundEvents.java
  src/main/java/com/minecolonies/coremod/util/SoundUtils.java
  src/main/resources/assets/minecolonies/gui/townhall/layoutactions.xml
  src/main/resources/assets/minecolonies/gui/townhall/windowtownhallhirecitizen.xml
  src/main/resources/assets/minecolonies/lang/en_us.lang
  src/main/resources/assets/minecolonies/sounds.json
  src/main/resources/assets/minecolonies/sounds/mob/citizen/child/laugh1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/citizen/child/laugh2.ogg
  src/main/resources/assets/minecolonies/textures/gui/citizen/colonist_request_button_dark.png
  src/main/resources/assets/minecolonies/textures/gui/citizen/colonist_request_button_light.png
Labels: ready

#3414 Fix Building limit
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractCitizenAssignable.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingArchery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBarracksTower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLibrary.java
Labels: ready
