Repository ldtteam/minecolonies, pull requests merged in 2021-07, with the labels that each got.

#7335 Allow stone smelter to learn more recipes
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
Labels: PR: Hotfix, PR: Ready for Review

#7344 Reload TEs with invalid data from default name.
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java
Labels: PR: Hotfix, PR: Ready for Review

#7345 fix 7343
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
Labels: PR: Hotfix, PR: Ready for Review

#7329 Raider spawning
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBarracksTower.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/AbstractShipRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/HordeRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRaiderPathing.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, System: Pathfinding

#7348 Bump minimum MC/Forge versions to match build.properties
  build.gradle
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7333 Some moar fixes
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowListRecipes.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/RecallCitizenHutMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/worker/RecallCitizenMessage.java
Labels: PR: Hotfix, PR: Ready for Review

#7355 Bump structurize
  build.properties
Labels: PR: Hotfix, PR: Ready for Review

#7356 Fix jumping
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/MovementHandler.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7352 Bring back the Build Building button
  src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java
Labels: PR: Hotfix, PR: Ready for Review

#7358 Remind gradle to rebuild mods.toml if build.properties changes
  build.gradle
Labels: PR: Hotfix, PR: Ready for Review

#7354 Miner interaction
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7370 Update tinkers compat
  src/api/java/com/minecolonies/api/compatibility/Compatibility.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/SlimeTreeCheck.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersToolHelper.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersToolProxy.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7367 Stuck handling fixes
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7366 fix 7225
  src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollColonyAreaTP.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollColonyTP.java
Labels: PR: Hotfix, PR: Ready for Review

#7364 Add error message when adding player
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHall.java
  src/main/resources/assets/minecolonies/gui/townhall/layoutpermissions.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7359 Craft fixes
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IBuildingModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/ISettingsModuleView.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/researches/effects/recipemodeunlock.json
  src/main/generated/resources/data/minecolonies/researches/technology/cheatsheet.json
  src/main/generated/resources/data/minecolonies/researches/technology/warehousemaster.json
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowSuggestBuildTool.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowListRecipes.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/CrafterRecipeSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/SwitchBuildingWithToolMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7371 more forgiving pickup logic
  src/api/java/com/minecolonies/api/tileentities/AbstractTileEntityColonyBuilding.java
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyBuilding.java
  src/api/java/com/minecolonies/api/util/InventoryUtils.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7381 Schem fixes
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/blacksmith4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/tavern3.blueprint
  src/main/resources/assets/minecolonies/schematics/nordic/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/nordic/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/nordic/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/nordic/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/nordic/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/bayou1.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/big_pirate_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/graveyard1.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/graveyard2.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/graveyard3.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/graveyard4.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/graveyard5.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/stone/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/jungletownhallsupplycamp.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#7374 Fix citizen armor updates - 6905
  src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIFight.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/minecolonies/gui/townhall/layoutcitizens.xml
Labels: PR: Hotfix, PR: Ready for Review

#7376 Adjustments for parent buildings/schematics
  src/api/java/com/minecolonies/api/colony/buildings/ISchematicProvider.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingContainer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java
  src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuild.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7377 Do LevenshteinDistance setting.
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowPostBox.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowSelectRes.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7378 Some guard imp
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/util/SoundUtils.java
Labels: PR: Hotfix, PR: Ready for Review

#7383 Finish refactor
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyFlag.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowModuleBuilding.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowAssignCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowBannerPicker.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/AbstractWindowTownHall.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowCitizenPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowHappinessPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowInfoPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowMainPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHallColonyManage.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowWorkOrderPage.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java
  src/main/resources/assets/minecolonies/gui/townhall/layoutactions.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutcitizens.xml
  src/main/resources/assets/minecolonies/gui/townhall/layouthappiness.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutinfo.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutpermissions.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutsettings.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutworkorder.xml
  src/main/resources/assets/minecolonies/gui/townhall/windowtownhall.xml
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, System: GUI

#7382 Bump JEI and cache recipes to improve startup perf
  build.properties
  src/main/java/com/minecolonies/coremod/compatibility/jei/CompostRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JobBasedRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/PrivateCraftingTeachingTransferHandler.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7395 Fixes the "requires crafter X" item tooltips
  src/main/java/com/minecolonies/coremod/event/ClientEventHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7394 Fix JEI lookup for smelting recipes
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
Labels: PR: Hotfix, PR: Ready for Review

#7392 fix 7389
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
Labels: PR: Hotfix, PR: Ready for Review

#7411 barrackstowerhotfix
  src/main/java/com/minecolonies/coremod/placementhandlers/BarracksTowerHandler.java
  src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlerInitializer.java
Labels: PR: Hotfix, PR: Ready for Review

#7409 rs fixes
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractCraftingRequestResolver.java
Labels: PR: Hotfix, PR: Ready for Review, System: Request System

#7398 Add threat tables to citizens/guards
  src/api/java/com/minecolonies/api/entity/combat/combat/IThreatTableEntity.java
  src/api/java/com/minecolonies/api/entity/combat/combat/ThreatTable.java
  src/api/java/com/minecolonies/api/entity/combat/combat/ThreatTableEntry.java
  src/api/java/com/minecolonies/api/entity/mobs/AbstractEntityMinecoloniesMob.java
  src/api/java/com/minecolonies/api/util/constant/GuardConstants.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenAvoidEntity.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7401 Add sleeping and mourning interactions
  src/api/java/com/minecolonies/api/colony/ICitizenDataView.java
  src/api/java/com/minecolonies/api/colony/interactionhandling/ChatPriority.java
  src/api/java/com/minecolonies/api/entity/citizen/citizenhandlers/ICitizenMournHandler.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/client/render/RenderBipedCitizen.java
  src/main/java/com/minecolonies/coremod/colony/CitizenDataView.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenMournHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7430 Fix norsemen and pirate ships
  src/main/resources/assets/minecolonies/schematics/ships/big_norsemen_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/big_pirate_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/medium_norsemen_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/medium_pirate_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/small_norsemen_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/small_pirate_ship.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#7426 Minor fixes
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowHutMinerModule.java
Labels: PR: Hotfix, PR: Ready for Review

#7432 More crafts
  src/main/resources/data/minecolonies/tags/items/cook_ingredient.json
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
  src/main/resources/data/minecolonies/tags/items/stonemason_ingredient.json
Labels: PR: Hotfix, PR: Ready for Review

#7431 Closes #7304
  src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7433 Show hutblock coordinates when making a build order
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7453 Solve couriers stuck
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java
Labels: PR: Hotfix, PR: Ready for Review
