Repository ldtteam/minecolonies, pull requests merged in 2021-08, with the labels that each got.

#7427 Crafting improvements
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7439 Schem updates from Thaylar
  src/main/resources/assets/minecolonies/schematics/asian/chickenherder1.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/chickenherder2.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/chickenherder3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/smeltery3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/smeltery4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/smeltery5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/guardtower1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/guardtower2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/guardtower3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/guardtower4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/guardtower5.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/waystone_deco.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/caledonia/waystone_deco.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/caledonia/gate_red_double.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/caledonia/gate_red_single.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/caledonia/gatehouse_red_double.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/caledonia/gatehouse_red_single.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#7458 Some fixes
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowDecorationController.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/entity/NewBobberEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/fisherman/EntityAIWorkFisherman.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenExperienceHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/server/DecorationControllerUpdateMessage.java
  src/main/java/com/minecolonies/coremod/tileentities/TileEntityDecorationController.java
Labels: PR: Hotfix, PR: Ready for Review

#7455 Small fixes
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/ItemListModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/util/BuildingStructureHandler.java
  src/main/java/com/minecolonies/coremod/items/ItemBannerRallyGuards.java
  src/main/java/com/minecolonies/coremod/util/WorkerUtil.java
Labels: PR: Hotfix, PR: Ready for Review

#7452 add combat ai based on threattables for both raiders and guards
  .idea/inspectionProfiles/profiles_settings.xml
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/entity/ai/IStateAI.java
  src/api/java/com/minecolonies/api/entity/ai/registry/IMobAIRegistry.java
  src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java
  src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java
  src/api/java/com/minecolonies/api/entity/combat/CombatAIStates.java
  src/api/java/com/minecolonies/api/entity/combat/threat/IThreatTableEntity.java
  src/api/java/com/minecolonies/api/entity/combat/threat/ThreatTable.java
  src/api/java/com/minecolonies/api/entity/combat/threat/ThreatTableEntry.java
  src/api/java/com/minecolonies/api/entity/mobs/AbstractEntityMinecoloniesMob.java
  src/api/java/com/minecolonies/api/entity/mobs/RaiderMobUtils.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathResult.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java
  src/api/java/com/minecolonies/api/util/constant/GuardConstants.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/TavernBuildingModule.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractAISkeleton.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIFight.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/KnightCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/RangerCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/combat/AttackMoveAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/combat/CombatUtils.java
  src/main/java/com/minecolonies/coremod/entity/ai/combat/TargetAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/registry/MobAIRegistry.java
  src/main/java/com/minecolonies/coremod/entity/citizen/CitizenColonyHandler.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/EntityAIAttackArcher.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/EntityAIRaiderAttackMelee.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/EntityAIWalkToRandomHuts.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderMeleeAI.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderRangedAI.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderWalkAI.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRaiderPathing.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRandomPos.java
  src/main/java/com/minecolonies/coremod/util/TeleportHelper.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7464 Fix whirlwind hitting non-targets
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/KnightCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/combat/TargetAI.java
Labels: PR: Hotfix, PR: Ready for Review

#7472 Set tool and sounds for composted dirt
  src/main/java/com/minecolonies/coremod/blocks/BlockCompostedDirt.java
Labels: PR: Ready for Review, PR: Hotfix

#7482 Hotfix citizens not getting equipped item stats
  src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenItemHandler.java
Labels: PR: Ready for Review, PR: Hotfix

#7468 Custom visitors
  src/api/java/com/minecolonies/api/client/render/modeltype/CitizenModel.java
  src/api/java/com/minecolonies/api/colony/ICitizenData.java
  src/api/java/com/minecolonies/api/colony/ICitizenDataView.java
  src/api/java/com/minecolonies/api/colony/ICivilianData.java
  src/api/java/com/minecolonies/api/colony/IColonyView.java
  src/api/java/com/minecolonies/api/colony/IVisitorData.java
  src/main/java/com/minecolonies/coremod/client/render/RenderBipedCitizen.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/CitizenDataView.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/VisitorData.java
  src/main/java/com/minecolonies/coremod/colony/VisitorDataView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/TavernBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/interactionhandling/RecruitmentInteraction.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/datalistener/CustomVisitorListener.java
  src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/client/colony/ColonyVisitorViewDataMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/visitors/example.json
Labels: PR: Merge on Monday-Wednesday

#7495 Guard scroll fix/builder request fix
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
Labels: PR: Ready for Review, PR: Hotfix

#7485 Add hover for Supporter feature
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Hotfix

#7497 Overrule stuck parents - adjust clipboard to show tree
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowRequestTree.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowClipBoard.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardRetryingRequestResolver.java
Labels: System: Request System, PR: Ready for Review, PR: Merge on Monday-Wednesday

#7500 Study improvement, solve deprecated, assistant interference improvement
  src/main/java/com/minecolonies/coremod/MineColonies.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/MinimumStockModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIUsesFurnace.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
Labels: PR: Ready for Review, PR: Hotfix

#7501 Fix/7479
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowListRecipes.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/CraftingModuleView.java
  src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractAISkeleton.java
Labels: PR: Ready for Review, PR: Hotfix

#7520 Performance improvements + new builder setting
  build.properties
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/researches/effects/buildermodeunlock.json
  src/main/generated/resources/data/minecolonies/researches/technology/buildermodes.json
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowPostBox.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowSelectRes.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/EntityListModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/ItemListModuleWindow.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/BuilderModeSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/CrafterRecipeSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBuilder.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/colony/workorders/AbstractWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7533 Hotfix citizendata tick cme
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenSleepHandler.java
Labels: PR: Ready for Review, PR: Hotfix

#7544 Fix guard xp
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/KnightCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/RangerCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/combat/TargetAI.java
Labels: PR: Ready for Review, PR: Hotfix

#7545 Decoration controllers upgrade issue
  src/main/java/com/minecolonies/coremod/client/gui/WindowDecorationController.java
Labels: PR: Ready for Review, PR: Hotfix

#7543 Prune cmd single world
  src/main/java/com/minecolonies/coremod/commands/generalcommands/CommandPruneWorld.java
Labels: PR: Ready for Review, PR: Hotfix

#7541 Add Hyrios patreon reward
  src/main/java/com/minecolonies/coremod/colony/VisitorData.java
  src/main/java/com/minecolonies/coremod/colony/VisitorDataView.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/visitors/hyrios.json
Labels: PR: Ready for Review, PR: Hotfix

#7542 Fix weird behaviour when building a guard tower or barracks
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7509 fix item registry poll
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
Labels: PR: Ready for Review, PR: Hotfix
