Repository ldtteam/minecolonies, pull requests merged in 2021-03, with the labels that each got.

#6615 Manual changes
  build.properties
  src/api/java/com/minecolonies/api/util/CompatibilityUtils.java
  src/api/java/com/minecolonies/api/util/DebugUtil.java
  src/api/java/com/minecolonies/api/util/InventoryFunctions.java
  src/api/java/com/minecolonies/api/util/MathUtils.java
  src/api/java/com/minecolonies/api/util/Pond.java
  src/api/java/com/minecolonies/api/util/RSConstants.java
  src/api/java/com/minecolonies/api/util/constant/BuildingConstants.java
  src/api/java/com/minecolonies/api/util/constant/CitizenConstants.java
  src/api/java/com/minecolonies/api/util/constant/ColonyConstants.java
  src/api/java/com/minecolonies/api/util/constant/ColonyManagerConstants.java
  src/api/java/com/minecolonies/api/util/constant/ColorConstants.java
  src/api/java/com/minecolonies/api/util/constant/Constants.java
  src/api/java/com/minecolonies/api/util/constant/GuardConstants.java
  src/api/java/com/minecolonies/api/util/constant/InventoryConstants.java
  src/api/java/com/minecolonies/api/util/constant/Literals.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/RaiderConstants.java
  src/api/java/com/minecolonies/api/util/constant/SchematicTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/StructureTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/Suppression.java
  src/api/java/com/minecolonies/api/util/constant/ToolLevelConstants.java
  src/api/java/com/minecolonies/api/util/constant/TypeConstants.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/blocks/BlockDecorationController.java
  src/main/java/com/minecolonies/coremod/blocks/decorative/BlockConstructionTape.java
  src/main/java/com/minecolonies/coremod/blocks/schematic/BlockWaypoint.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutLumberjack.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/CustomArrowEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIFight.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/java/com/minecolonies/coremod/util/BuildingUtils.java
  src/main/java/com/minecolonies/coremod/util/CreativeRaiderStructureHandler.java
  src/main/java/com/minecolonies/coremod/util/ModifyableLambdaWrapper.java
  src/main/java/com/minecolonies/coremod/util/PermissionUtils.java
  src/main/java/com/minecolonies/coremod/util/WorkerUtil.java
  src/main/resources/assets/minecolonies/gui/windowhutguardtower.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6638 Update Gentoo specific java installation instructions
  README.md
Labels: PR: Ready for Review

#6648 Add new mystical site schems
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/townhall4.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/kelp_farm1.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/kelp_farm2.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/kelp_farm3.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/mystic_pagoda1.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/mystic_pagoda2.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/mystic_pagoda3.blueprint
  src/main/resources/assets/minecolonies/schematics/infrastructure/hutblocks/mysticalsitehut.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/mysticalsite5.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6658 Fix caledonia house using jungle shingles
  src/main/resources/assets/minecolonies/schematics/caledonia/citizen3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/citizen4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/citizen5.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6652 Use correct Java source encoding
  build.gradle
Labels: PR: Ready for Review

#6659 Disable chests, improve tool keeping
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyBuilding.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingContainer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingWareHouse.java
Labels: PR: Ready for Review

#6661 Builder and pathing adjustments
  src/api/java/com/minecolonies/api/entity/pathfinding/AbstractAdvancedPathNavigate.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathFindingStatus.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathResult.java
  src/api/java/com/minecolonies/api/entity/pathfinding/RandomPathResult.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRandomPos.java
Labels: PR: Ready for Review, System: Pathfinding

#6667 bump structurize
  build.properties
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/META-INF/mods.toml
Labels: PR: Ready for Review

#6635 Add a flag to mark colonies as abandoned allowing them to be destroyed.
  src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java
Labels: 1.16, PR: Ready for Review

#6587 Enable tool retention/durability burn
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Stack.java
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/api/java/com/minecolonies/api/util/InventoryUtils.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingCrafter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/crafting/RecipeStorageFactory.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractCraftingProductionResolver.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractCraftingRequestResolver.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/crusher/EntityAIWorkCrusher.java
  src/main/resources/data/minecolonies/crafterrecipes/sifter/dirt.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/gravel.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/sand.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/soul_sand.json
Labels: PR: Ready for Review

#6640 Add guard task to patrol mines
  src/api/java/com/minecolonies/api/colony/buildings/IGuardBuilding.java
  src/api/java/com/minecolonies/api/entity/ai/citizen/guards/GuardTask.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutGuardTower.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBarracksTower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/Level.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/EntityCitizenWalkToProxy.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/guard/GuardSetMinePosMessage.java
  src/main/resources/assets/minecolonies/gui/windowhutguardtower.xml
  src/main/resources/assets/minecolonies/gui/windowhutminer.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6696 Add back missing armor textures
  src/main/resources/assets/minecolonies/textures/models/armor/pirate2_layer_1.png
  src/main/resources/assets/minecolonies/textures/models/armor/pirate2_layer_2.png
  src/main/resources/assets/minecolonies/textures/models/armor/pirate_layer_1.png
  src/main/resources/assets/minecolonies/textures/models/armor/pirate_layer_2.png
  src/main/resources/assets/minecolonies/textures/models/armor/santa_hat_layer_1.png
Labels: PR: Hotfix, PR: Ready for Review

#6695 fix #6683 6694
  src/main/java/com/minecolonies/coremod/event/DebugRendererChunkBorder.java
  src/main/java/com/minecolonies/coremod/util/BackUpHelper.java
Labels: PR: Hotfix, PR: Ready for Review

#6692 Sort items by activeness making it easier to see selected items
  src/main/java/com/minecolonies/coremod/client/gui/ViewFilterableList.java
Labels: PR: Ready for Review, System: GUI

#6702 Building completed coordinates
  src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6703 Change standardRequests hover label
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/StandardRequests.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, System: GUI

#6706 Improve backup loading
  src/api/java/com/minecolonies/api/colony/IColonyManager.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/colony/IColonyManagerCapability.java
  src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java
  src/main/java/com/minecolonies/coremod/util/BackUpHelper.java
Labels: PR: Ready for Review

#6693 Fix Research "Open To LAN" Support
  src/main/generated/resources/data/minecolonies/researches/technology/letitgrow.json
  src/main/java/com/minecolonies/coremod/datalistener/ResearchListener.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
Labels: PR: Ready for Review

#6682 fix #6672
  src/main/java/com/minecolonies/coremod/client/gui/WindowGuardControl.java
Labels: PR: Hotfix, PR: Ready for Review, System: GUI

#6642 Move to module filterablelist
  .idea/inspectionProfiles/Minecolonies.xml
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IBuildingModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IItemListModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IPersistentModule.java
  src/api/java/com/minecolonies/api/colony/buildings/registry/BuildingEntry.java
  src/api/java/com/minecolonies/api/colony/buildings/views/IBuildingView.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractHutFilterableLists.java
  src/main/java/com/minecolonies/coremod/client/gui/ViewFilterableList.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutComposter.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCook.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutFlorist.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingContainer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingFurnaceUser.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractFilterableListBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractFilterableListCrafter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/ItemListModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/ItemListModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/registry/BuildingDataManager.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractFilterableListsView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingComposter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingWareHouse.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAISleep.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIVisitor.java
  src/main/java/com/minecolonies/coremod/entity/citizen/VisitorCitizen.java
  src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/AssignFilterableItemMessage.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6721 Fix inverted sortable lists
  src/main/java/com/minecolonies/coremod/client/gui/ViewFilterableList.java
Labels: PR: Ready for Review, System: GUI

#6718 Fix some GUI issues
  src/main/resources/assets/minecolonies/gui/layouthuts/layouthutpageactionsminwoinv.xml
  src/main/resources/assets/minecolonies/gui/townhall/layoutinfo.xml
  src/main/resources/assets/minecolonies/gui/windowassigncitizen.xml
  src/main/resources/assets/minecolonies/gui/windowbuildbuilding.xml
  src/main/resources/assets/minecolonies/gui/windowhutguardtower.xml
Labels: PR: Hotfix, PR: Ready for Review, System: GUI

#6713 Do proper water checking
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Ready for Review, Port to PVI, System: Pathfinding

#6732 Fix comment for neighbor building rendering option
  src/api/java/com/minecolonies/api/configuration/ClientConfiguration.java
Labels: PR: Hotfix, PR: Ready for Review

#6729 fix 6709
  src/main/java/com/minecolonies/coremod/client/gui/WindowListRecipes.java
  src/main/resources/assets/minecolonies/gui/windowlistrecipes.xml
Labels: PR: Hotfix, PR: Ready for Review, System: GUI

#6719 Simplify crushing.
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6739 Fix Night Owl Research Effects
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenSleepHandler.java
Labels: PR: Hotfix, PR: Ready for Review

#6726 Tool Texture Cleanup, Claim command messages, max limit to Builder progress-needed
  src/main/java/com/minecolonies/coremod/commands/colonycommands/CommandClaimChunks.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/textures/items/scepterbeekeeper.png
  src/main/resources/assets/minecolonies/textures/items/sceptergold.png
  src/main/resources/assets/minecolonies/textures/items/scepterguard.png
  src/main/resources/assets/minecolonies/textures/items/scepterlumberjack.png
  src/main/resources/assets/minecolonies/textures/items/scepterpermission.png
  src/main/resources/assets/minecolonies/textures/items/sceptersteel.png
  src/main/resources/assets/minecolonies/textures/items/scrollblue.png
  src/main/resources/assets/minecolonies/textures/items/scrollmagic.png
  src/main/resources/assets/minecolonies/textures/items/scrollred.png
  src/main/resources/assets/minecolonies/textures/items/scrollrune.png
  src/main/resources/assets/minecolonies/textures/items/scrollruneup.png
Labels: PR: Hotfix, PR: Ready for Review

#6691 Move composting to vanilla-style datapack recipe and include JEI lookup.
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/crafting/CompostRecipe.java
  src/api/java/com/minecolonies/api/crafting/CountedIngredient.java
  src/api/java/com/minecolonies/api/items/ModTags.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutComposter.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/CompostRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/RenderHelper.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
  src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java
  src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java
  src/main/java/com/minecolonies/coremod/recipes/FoodIngredient.java
  src/main/java/com/minecolonies/coremod/recipes/PlantIngredient.java
  src/main/java/com/minecolonies/coremod/tileentities/TileEntityBarrel.java
  src/main/java/com/minecolonies/coremod/util/FurnaceRecipes.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/recipes/compostables.json
  src/main/resources/data/minecolonies/recipes/compostables_poor.json
  src/main/resources/data/minecolonies/recipes/compostables_rich.json
  src/main/resources/data/minecolonies/tags/items/compostables.json
  src/main/resources/data/minecolonies/tags/items/compostables_poor.json
  src/main/resources/data/minecolonies/tags/items/compostables_rich.json
Labels: Compatibility: Mod, PR: Not Ready, System: Request System

#6716 Schem fixes and updates
  src/main/resources/assets/minecolonies/schematics/caledonia/florist1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/florist2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/florist3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse5.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/cornerinside.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/warehouse1.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/warehouse2.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/warehouse3.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/warehouse4.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/warehouse5.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/cornerrailroad1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/cornerrailroad2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/cornerrailroad3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/intersectrail1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/intersectrail2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/intersectrail3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/longrailroad1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/longrailroad2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/longrailroad3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/minirail1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/minirail2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/minirail3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/shortrailroad1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/shortrailroad2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/shortrailroad3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/trail1.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/trail2.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/trail3.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/tunnelintersect.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/tunnellong.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/tunnelmini.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/tunnelshort.blueprint
  src/main/resources/assets/minecolonies/schematics/rail/fortress/tunnelt.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction3.blueprint
  src/main/resources/assets/minecolonies/schematics/statues/stone_lion_b.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/junglesupplycamp_alt.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_a.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_b.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_corner.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_corner_a.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_corner_addon.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_corner_b.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_gate.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_long.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_medal.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_medal_bw.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_medal_rw.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_medalbig_bw.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_medalbig_rw.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_stair.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_straight_addon.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_tee.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_tower.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/big_wall_x.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6723 Specifies colony name in chat messages
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/LivingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/AbstractShipRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/HordeRaidEvent.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#6745 Lets you smelt iron scimitars to get iron nuggets
  src/main/resources/data/minecolonies/recipes/iron_nugget_from_iron_scimitar_blasting.json
  src/main/resources/data/minecolonies/recipes/iron_nugget_from_iron_scimitar_smelting.json
Labels: PR: Hotfix, PR: Ready for Review

#6755 Fix scimitars
  src/main/resources/data/minecolonies/recipes/iron_nugget_from_iron_scimitar_blasting.json
Labels: PR: Hotfix, PR: Ready for Review

#6758 Fix gate state/reset
  src/api/java/com/minecolonies/api/blocks/decorative/AbstractBlockGate.java
Labels: PR: Hotfix, PR: Ready for Review

#6756 Chest Resource search UI fix
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyBuilding.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java
Labels: PR: Hotfix, PR: Ready for Review

#6722 Improve Research Branch Customizability
  src/api/java/com/minecolonies/api/research/AbstractResearchProvider.java
  src/api/java/com/minecolonies/api/research/IGlobalResearchBranch.java
  src/api/java/com/minecolonies/api/research/IGlobalResearchTree.java
  src/api/java/com/minecolonies/api/research/ResearchBranchType.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/generated/resources/data/minecolonies/researches/civilian.json
  src/main/generated/resources/data/minecolonies/researches/combat.json
  src/main/generated/resources/data/minecolonies/researches/effects/happinessmultiplier.json
  src/main/generated/resources/data/minecolonies/researches/technology.json
  src/main/generated/resources/data/minecolonies/researches/technology/heavilyloaded.json
  src/main/generated/resources/data/minecolonies/researches/unlockable.json
  src/main/generated/resources/data/minecolonies/researches/unlockable/diamondmesh.json
  src/main/generated/resources/data/minecolonies/researches/unlockable/flintmesh.json
  src/main/generated/resources/data/minecolonies/researches/unlockable/ironmesh.json
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutUniversityModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/managers/ResearchManager.java
  src/main/java/com/minecolonies/coremod/datalistener/ResearchListener.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearch.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearchBranch.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearchFactory.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearchTree.java
  src/main/java/com/minecolonies/coremod/research/LocalResearch.java
  src/main/java/com/minecolonies/coremod/research/LocalResearchTree.java
  src/main/resources/assets/minecolonies/gui/windowhutuniversity.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6750 Minimum stock to module port
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IAltersRequiredItems.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IItemListModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IMinimumStockModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IMinimumStockModuleView.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/ItemListModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/MinimumStockModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCookModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutSifterModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutWareHouse.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowSelectRes.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/MinimumStockModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/ItemListModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/MinimumStockModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/AddMinimumStockToBuildingModuleMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/RemoveMinimumStockFromBuildingModuleMessage.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutminimumstock.xml
  src/main/resources/assets/minecolonies/gui/windowhutbaker.xml
  src/main/resources/assets/minecolonies/gui/windowhutcomposter.xml
  src/main/resources/assets/minecolonies/gui/windowhutcook.xml
  src/main/resources/assets/minecolonies/gui/windowhutsifter.xml
  src/main/resources/assets/minecolonies/gui/windowhutwarehouse.xml
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6764 Remove unnecessary classes
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCookModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutDyerModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutFloristModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutGlassblowerModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutSmelterModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGlassblower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
  src/main/resources/assets/minecolonies/gui/windowhutbaker.xml
  src/main/resources/assets/minecolonies/gui/windowhutcook.xml
  src/main/resources/assets/minecolonies/gui/windowhutdyer.xml
  src/main/resources/assets/minecolonies/gui/windowhutflorist.xml
  src/main/resources/assets/minecolonies/gui/windowhutsmelter.xml
Labels: PR: Hotfix, PR: Ready for Review

#6772 Fixes a cullface issue
  src/main/resources/assets/minecolonies/models/block/composteddirt.json
Labels: PR: Hotfix, PR: Ready for Review

#6768 Schem updates
  src/main/resources/assets/minecolonies/schematics/caledonia/builder1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/builder2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/builder3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/builder4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/builder5.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/caledonia/field_big1.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/caledonia/field_big2.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/caledonia/field_big3.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/caledonia/field_big4.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep1.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep2.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep3.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_a1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_a2.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_b1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_b2.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_c1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wall_c2.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_a1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_a2.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_b1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_b2.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_c1.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/asian/wallmid_c2.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6626 Resourceful Bees compatibility
  build.gradle
  build.properties
  src/api/java/com/minecolonies/api/compatibility/Compatibility.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/resourcefulbees/IBeehiveCompat.java
  src/api/java/com/minecolonies/api/compatibility/resourcefulbees/ResourcefulBeesCompat.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
Labels: Compatibility: Mod, PR: Merge on Monday-Wednesday, PR: Not Ready, PR: Ready for Review

#6781 Fix particle texture
  src/main/resources/assets/minecolonies/models/block/blockhutuniversity.json
Labels: PR: Hotfix, PR: Ready for Review

#6779 Schem updates
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep1.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep2.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep3.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/asiansupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/birchsupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/darkoaksupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/fortresssupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/medievaloaksupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/medievalsprucesupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/mesasupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/nordicsupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/sandstonesupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/warpedsupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/woodensupplycamp.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/fortresssupplyship.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/medievaloaksupplyship.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/medievalsprucesupplyship.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/nordicsupplyship.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/stonesupplyship.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6778 Crafting fixes
  src/main/resources/data/minecolonies/tags/items/compostables.json
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
Labels: PR: Hotfix, PR: Ready for Review

#6761 Tidy crafting
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipeManager.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6785 Fix compostables after #6778
  src/main/resources/data/minecolonies/tags/items/compostables.json
Labels: PR: Hotfix, PR: Ready for Review

#6789 Fix Lumberjack responding to RS
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/UpdateHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/update/implementation/ResetRSToFixLumberjack.java
Labels: PR: Hotfix, PR: Ready for Review

#6786 Add interaction requesting Mesh if there is none
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/sifter/EntityAIWorkSifter.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#6794 Hotfix/recipebimap
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRecipeManager.java
Labels: PR: Hotfix, PR: Ready for Review

#6795 Add gradle.xml to gitignore
  .gitignore
  .idea/gradle.xml
Labels: PR: Hotfix, PR: Ready for Review

#6796 Remove duplicates in the gitignore
  .gitignore
Labels: PR: Hotfix, PR: Ready for Review

#6774 Colonists go to sleep instead of walking around in the rain
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
Labels: PR: Hotfix, PR: Ready for Review

#6800 fix lumberjack CME
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
Labels: PR: Hotfix, PR: Ready for Review

#6769 Chance for the Composter to make podzol instead of dirt
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/researches/effects/podzolchancemultiplier.json
  src/main/generated/resources/data/minecolonies/researches/technology/podzolchance.json
  src/main/generated/resources/data/minecolonies/researches/technology/podzolchance2.json
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6797 Fix oak stairs causing sawmill to learn oak-oak timberframes
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
Labels: PR: Hotfix, PR: Ready for Review

#6806 Feature/task list
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCrafterModule.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCrafterTaskModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/CrafterTaskModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/CrafterTaskModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBlacksmith.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingConcreteMixer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDeliveryman.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFletcher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMechanic.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layouttasklist.xml
  src/main/resources/assets/minecolonies/gui/windowhutcrafter.xml
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6807 Improve raider spawn Y
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
Labels: PR: Hotfix, PR: Ready for Review

#6802 Ensure the farmer dumps after crafting.
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
Labels: PR: Hotfix, PR: Ready for Review

#6818 hotfix adding supply loot to all tables
  src/main/java/com/minecolonies/coremod/loot/SupplyLoot.java
Labels: PR: Hotfix, PR: Ready for Review

#6821 Fix deletion of all recipes
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
Labels: Critical, PR: Hotfix, PR: Ready for Review

#6823 Stop monsters spawn, mark dirty on change, buildingmanager cleanup
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6822 Better fluid handling, small fixes
  src/api/java/com/minecolonies/api/util/InventoryUtils.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowSelectRes.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/placementhandlers/DimensionFluidHandler.java
  src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlerInitializer.java
Labels: PR: Hotfix, PR: Ready for Review

#6825 Minor fixes
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_acacia_log2.json
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_birch_log2.json
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_dark_oak_log2.json
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_jungle_log2.json
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_oak_log2.json
  src/main/resources/data/minecolonies/crafterrecipes/lumberjack/stripped_spruce_log2.json
Labels: PR: Hotfix, PR: Ready for Review

#6826 Add JEI recipe transfer for furnace (mostly for Stone Smeltery).
  src/api/java/com/minecolonies/api/inventory/container/ContainerCraftingFurnace.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/PrivateCraftingTeachingTransferHandler.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/PrivateSmeltingTeachingTransferHandler.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/TransferRecipeCraftingTeachingMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6798 Disease Config File Improvements, Better Compatibility Manager Reloading, Research Fixes
  build.gradle
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/items/ModTags.java
  src/api/java/com/minecolonies/api/research/AbstractResearchProvider.java
  src/main/generated/resources/data/minecolonies/researches/civilian/healingcream.json
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/java/com/minecolonies/coremod/MineColonies.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenDiseaseHandler.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/event/TagWorkAroundEventHandler.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/java/com/minecolonies/coremod/util/FurnaceRecipes.java
  src/main/resources/data/minecolonies/tags/items/florist_flowers.json
  src/main/resources/data/minecolonies/tags/items/florist_flowers_excluded.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6829 fixup plantation 6815
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutPlantationModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java
Labels: PR: Hotfix, PR: Ready for Review

#6836 Improve food interaction handling
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
Labels: PR: Hotfix, PR: Ready for Review

#6840 cache number of slots
  src/api/java/com/minecolonies/api/inventory/api/CombinedItemHandler.java
Labels: PR: Hotfix, PR: Ready for Review

#6835 Add some recipe bullet-proofing
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRecipeManager.java
Labels: Critical, PR: Hotfix, PR: Ready for Review
