Repository ldtteam/minecolonies, pull requests merged in 2021-09, with the labels that each got.

#7558 Adds two general utility schematics
  src/main/resources/assets/minecolonies/schematics/dig.blueprint
  src/main/resources/assets/minecolonies/schematics/fill.blueprint
Labels: PR: Ready for Review, PR: Schematics, PR: Hotfix

#7571 fix dyn tree max
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
Labels: PR: Ready for Review, PR: Hotfix

#7567 Solve 7559
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/main/java/com/minecolonies/coremod/client/gui/citizen/RequestWindowCitizen.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/BuildingResourcesModule.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIUsesFurnace.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/healer/EntityAIWorkHealer.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/planter/EntityAIWorkPlanter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/school/EntityAIWorkTeacher.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
Labels: PR: Ready for Review, PR: Hotfix

#7574 Improve backup handling
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/commands/generalcommands/CommandBackup.java
  src/main/java/com/minecolonies/coremod/util/BackUpHelper.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Hotfix

#7573 Fix javadoc errors
  src/api/java/com/minecolonies/api/colony/ICitizenData.java
  src/api/java/com/minecolonies/api/colony/IColonyManager.java
  src/api/java/com/minecolonies/api/colony/jobs/IJob.java
  src/api/java/com/minecolonies/api/colony/requestsystem/factory/IFactory.java
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/deliveryman/AbstractDeliverymanRequestable.java
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/api/java/com/minecolonies/api/inventory/container/ContainerBuildingInventory.java
  src/api/java/com/minecolonies/api/inventory/container/ContainerCitizenInventory.java
  src/api/java/com/minecolonies/api/research/effects/registry/ResearchEffectEntry.java
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/api/java/com/minecolonies/api/util/Utils.java
  src/api/java/com/minecolonies/api/util/constant/BuildingConstants.java
  src/api/java/com/minecolonies/api/util/constant/UndertakerConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutSchoolModule.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
  src/main/java/com/minecolonies/coremod/entity/NewBobberEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/ConstructionTapeHelper.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java
  src/main/java/com/minecolonies/coremod/event/TagWorkAroundEventHandler.java
  src/main/java/com/minecolonies/coremod/tileentities/ScarecrowTileEntity.java
Labels: PR: Ready for Review, PR: Hotfix

#7572 fix 7549
  src/api/java/com/minecolonies/api/entity/ai/statemachine/states/AIWorkerState.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/trainingcamps/EntityAIArcherTraining.java
Labels: PR: Ready for Review, PR: Hotfix

#7569 Better standing up handling.
  src/api/java/com/minecolonies/api/util/EntityUtils.java
  src/main/java/com/minecolonies/coremod/entity/SittingEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenSleepHandler.java
Labels: PR: Ready for Review, PR: Hotfix

#7575 Fix/7568
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
Labels: PR: Ready for Review, PR: Hotfix

#7566 Integrate shape tool into survival/builder
  build.properties
  src/main/java/com/minecolonies/coremod/client/gui/WindowMinecoloniesBuildTool.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowMinecoloniesShapeTool.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java
  src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java
  src/main/java/com/minecolonies/coremod/proxy/IProxy.java
  src/main/resources/data/minecolonies/recipes/shapetool.json
Labels: Related: Structurize, PR: Ready for Review, PR: Merge on Monday-Wednesday

#7583 Move the dynamic trees size setting to the forester's hut
  src/api/java/com/minecolonies/api/entity/pathfinding/AbstractAdvancedPathNavigate.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/DynamicTreesSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobFindTree.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7588 Add groundlevel support to supply camps
  src/main/java/com/minecolonies/coremod/items/ItemSupplyCampDeployer.java
  src/main/java/com/minecolonies/coremod/items/ItemSupplyChestDeployer.java
Labels: PR: Ready for Review, PR: Hotfix

#7598 Backport fixes
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/UpdateHandler.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/citizen/VisitorCitizen.java
  src/main/resources/assets/minecolonies/models/block/blockhutcombatacademy.json
  src/main/resources/assets/minecolonies/textures/blocks/plate.png
Labels: PR: Ready for Review, PR: Hotfix

#7614 Fix grave spawn
  src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java
Labels: PR: Ready for Review, PR: Hotfix
