Repository ldtteam/minecolonies, pull requests merged in 2021-11, with the labels that each got.

#7740 Fix recipe comparison for enchanter JEI
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
Labels: PR: Ready for Review, PR: Hotfix

#7734 Create potatogod.json
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/visitors/potatogod.json
Labels: PR: Ready for Review, PR: Hotfix

#7746 Added deepslate stuff
  src/main/resources/data/minecolonies/tags/blocks/pathblocks.json
Labels: PR: Ready for Review, PR: Hotfix

#7748 Fix dyer not undying wool
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
Labels: PR: Ready for Review, PR: Hotfix

#7750 Fix the baker to use the Furnace again
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowListRecipes.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipeFactory.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutlistrecipes.xml
  src/main/resources/data/minecolonies/crafterrecipes/baker/bread.json
  src/main/resources/data/minecolonies/crafterrecipes/baker/cake.json
  src/main/resources/data/minecolonies/crafterrecipes/baker/cookie.json
  src/main/resources/data/minecolonies/crafterrecipes/baker/pumpkin_pie.json
Labels: PR: Ready for Review, PR: Hotfix

#7739 Solve two small issues
  src/main/java/com/minecolonies/coremod/client/gui/WindowSelectRes.java
  src/main/java/com/minecolonies/coremod/event/ClientEventHandler.java
Labels: PR: Ready for Review, PR: Hotfix

#7765 fix 7754
  src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java
Labels: PR: Ready for Review, PR: Hotfix

#7764 Move loot table analysis to later in the load sequence
  build.properties
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
  src/main/java/com/minecolonies/coremod/event/TagWorkAroundEventHandler.java
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7767 Fortress updates from Moobien
  src/main/resources/assets/minecolonies/schematics/fortress/fisherman1.blueprint
  src/main/resources/assets/minecolonies/schematics/fortress/fisherman2.blueprint
  src/main/resources/assets/minecolonies/schematics/fortress/fisherman3.blueprint
  src/main/resources/assets/minecolonies/schematics/fortress/fisherman4.blueprint
  src/main/resources/assets/minecolonies/schematics/fortress/fisherman5.blueprint
  src/main/resources/assets/minecolonies/schematics/fortress/townhall2.blueprint
Labels: PR: Ready for Review, PR: Schematics, PR: Hotfix

#7770 Some fixes
  src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
Labels: PR: Ready for Review, PR: Hotfix

#7784 Tidy and robustify tag loading events
  src/main/java/com/minecolonies/coremod/event/TagWorkAroundEventHandler.java
Labels: PR: Ready for Review, PR: Hotfix

#7771 better permission handling
  src/api/java/com/minecolonies/api/colony/IColonyView.java
  src/api/java/com/minecolonies/api/colony/permissions/Action.java
  src/api/java/com/minecolonies/api/colony/permissions/IPermissions.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java
  src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/citizen/VisitorCitizen.java
  src/main/java/com/minecolonies/coremod/network/messages/PermissionsMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7793 Fixes
  src/api/java/com/minecolonies/api/colony/buildings/IBuildingCanBeHiredFrom.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModuleView.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/WorkAtHomeBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/ArcherSquireModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/KnightSquireBuildingModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/StudentBuildingModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLibrary.java
Labels: PR: Ready for Review, PR: Hotfix

#7810 Adds JEI integration for animal herders (and the beekeeper)
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AnimalHerdingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingChickenHerder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCowboy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipeManager.java
  src/main/java/com/minecolonies/coremod/colony/crafting/LootTableAnalyzer.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/HerderRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JobBasedRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/RenderHelper.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/AbstractTeachingGuiHandler.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/CraftingGuiHandler.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/FurnaceCraftingGuiHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7808 Add excluded_food tag for food excluded from the restaurant by default
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IItemListModule.java
  src/api/java/com/minecolonies/api/items/ModTags.java
  src/api/java/com/minecolonies/api/util/constant/TagConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/ItemListModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPasteMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/ResetFilterableItemMessage.java
  src/main/resources/data/minecolonies/tags/items/excluded_food.json
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7795 Sky raiders
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/pirateEvent/ShipBasedRaiderUtils.java
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Hotfix

#7807 Adjustments
  src/api/java/com/minecolonies/api/entity/pathfinding/AbstractAdvancedPathNavigate.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java
  src/api/java/com/minecolonies/api/entity/pathfinding/SurfaceType.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/datagen/generated/minecolonies/assets/minecolonies/lang/default.json
  src/datagen/generated/minecolonies/data/minecolonies/researches/civilian/vines.json
  src/datagen/generated/minecolonies/data/minecolonies/researches/effects/vinesunlock.json
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/RangerCombatAI.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/trainingcamps/EntityAICombatTraining.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenAvoidEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/util/BuildingStructureHandler.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRaiderPathing.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday
