Repository ldtteam/minecolonies, pull requests merged in 2021-04, with the labels that each got.

#6830 Add colony export command
  src/main/java/com/minecolonies/coremod/commands/EntryPoint.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/CommandExportColony.java
  src/main/java/com/minecolonies/coremod/util/BackUpHelper.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6848 Make chunk claim message work for style names containing numbers
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
Labels: PR: Hotfix, PR: Ready for Review

#6847 Improve raider spawn points to be more variable
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/main/java/com/minecolonies/coremod/colony/VisitorData.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/TavernBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/pirateEvent/ShipBasedRaiderUtils.java
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollColonyTP.java
Labels: PR: Hotfix, PR: Ready for Review

#6843 Schem updates
  src/main/resources/assets/minecolonies/schematics/caledonia/composter1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/composter2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/composter5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/farmer1.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/farmer2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/farmer3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/farmer4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledoniaalternative/farmer5.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6854 Schem updates
  src/main/resources/assets/minecolonies/schematics/acacia/dyer1.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/dyer2.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/dyer3.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/dyer4.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/dyer5.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/dyer1.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/dyer2.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/dyer3.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/dyer4.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/dyer5.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/greenhouse1.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/greenhouse2.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/greenhouse3.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/greenhouse4.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/cave/2storyniceintersection.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/cave/2storyniceroad.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6856 Citizen Cap improvements, adjust Research GUI to match configs
  src/main/generated/resources/data/minecolonies/researches/effects/citizencapaddition.json
  src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingBuilderView.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/ResearchManager.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6857 fix server/client synch + cleanup
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/LivingBuildingModule.java
  src/main/resources/assets/minecolonies/gui/windowhuthome.xml
Labels: PR: Hotfix, PR: Ready for Review

#6865 Fix colonyflagbannercrash finally
  src/api/java/com/minecolonies/api/blocks/decorative/AbstractColonyFlagBanner.java
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyFlag.java
  src/main/java/com/minecolonies/coremod/items/ItemColonyFlagBanner.java
Labels: PR: Hotfix, PR: Ready for Review

#6872 hotfix recipes getting lost
  src/api/java/com/minecolonies/api/crafting/IRecipeStorageFactory.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/crafting/RecipeStorageFactory.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/worker/AddRemoveRecipeMessage.java
Labels: Critical, PR: Hotfix, PR: Ready for Review

#6866 Cleanup herders
  src/api/java/com/minecolonies/api/colony/buildings/modules/ISettingsModule.java
  src/api/java/com/minecolonies/coremod/generation/DataGeneratorConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowHerderModuleBuilding.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutGuide.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutBuilderModule.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutChickenHerderModule.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutCowboyModule.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutShepherdModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingHerder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/SettingsModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingChickenHerder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCowboy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingRabbitHutch.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSwineHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/AbstractEntityAIHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkCowboy.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkShepherd.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/cowboy/CowboySetMilkCowsMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/herder/HerderSetBreedingMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/shepherd/ShepherdSetDyeSheepsMessage.java
  src/main/resources/assets/minecolonies/gui/windowhutchickenherder.xml
  src/main/resources/assets/minecolonies/gui/windowhutcowboy.xml
  src/main/resources/assets/minecolonies/gui/windowhutshepherd.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6862 Convert ItemStack to ItemStorage in input
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/api/java/com/minecolonies/api/crafting/IRecipeStorageFactory.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowListRecipes.java
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCrafting.java
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowFurnaceCrafting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingConcreteMixer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGlassblower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/crafting/ItemStorageFactory.java
  src/main/java/com/minecolonies/coremod/colony/crafting/RecipeStorageFactory.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/crusher/EntityAIWorkCrusher.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/worker/AddRemoveRecipeMessage.java
  src/main/java/com/minecolonies/coremod/util/FurnaceRecipes.java
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/concretemixerfemale1_w.png
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6870 Improve possible server stall from large config values on colony creation
  src/api/java/com/minecolonies/api/colony/IColonyManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHallColonyManage.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/client/CreateColonyMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPasteMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPlaceMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#6875 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#6874 Fix food interaction handling
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
Labels: PR: Hotfix, PR: Ready for Review

#6881 fix 6880
  src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
Labels: PR: Hotfix, PR: Ready for Review

#6887 Fix raider spawn ontop of the nether
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
Labels: PR: Hotfix, PR: Ready for Review

#6907 Colony Color/Progress Settings, Fixes enableDebugLogging
  src/api/java/com/minecolonies/api/util/constant/ColonyConstants.java
  src/main/java/com/minecolonies/coremod/MineColonies.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/RequestSystemInitializer.java
  src/main/java/com/minecolonies/coremod/datalistener/ResearchListener.java
  src/main/java/com/minecolonies/coremod/research/ResearchEffectCategory.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#6901 Schem fixes
  src/main/resources/assets/minecolonies/schematics/birch/cowboy4.blueprint
  src/main/resources/assets/minecolonies/schematics/birch/cowboy5.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/treefarm.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/mysticalsite5.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6902 Lang fixes
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutBeekeeperModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java
  src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#6897 Improve food list
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
Labels: PR: Hotfix, PR: Ready for Review

#6921 Fix nether raiders spawning ontop
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
Labels: PR: Hotfix, PR: Ready for Review

#6890 Research UI Updates
  src/api/java/com/minecolonies/api/research/IGlobalResearchBranch.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java
  src/main/java/com/minecolonies/coremod/colony/managers/ResearchManager.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearch.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearchBranch.java
  src/main/java/com/minecolonies/coremod/research/LocalResearch.java
  src/main/java/com/minecolonies/coremod/research/LocalResearchTree.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/textures/gui/research/icon_cancel.png
  src/main/resources/assets/minecolonies/textures/gui/research/icon_check.png
  src/main/resources/assets/minecolonies/textures/gui/research/icon_start.png
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, System: GUI

#6933 Hive tool plays audio cue for adding/removing, in case you can't see chat
  src/main/java/com/minecolonies/coremod/items/ItemScepterBeekeeper.java
Labels: PR: Hotfix, PR: Ready for Review

#6941 Add crusher recipes for bonemeal.
  src/main/resources/data/minecolonies/crafterrecipes/crusher/bonemeal1.json
  src/main/resources/data/minecolonies/crafterrecipes/crusher/bonemeal2.json
  src/main/resources/data/minecolonies/crafterrecipes/crusher/bonemeal3.json
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
Labels: PR: Hotfix, PR: Ready for Review

#6910 Remove optional for modules, and add optional optional method
  src/api/java/com/minecolonies/api/colony/buildings/IBuilding.java
  src/api/java/com/minecolonies/api/colony/buildings/views/IBuildingView.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/ItemListModuleWindow.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingContainer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingFurnaceUser.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingComposter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/AbstractEntityAIHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkCowboy.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkShepherd.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAISleep.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIVisitor.java
  src/main/java/com/minecolonies/coremod/entity/citizen/VisitorCitizen.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/AddMinimumStockToBuildingModuleMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/AssignFilterableItemMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/TriggerSettingMessage.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6903 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#6951 make getOwnBuilding not null
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIFight.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/AbstractEntityAIHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkCowboy.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
Labels: Needs Discussion, PR: Merge on Monday-Wednesday, PR: Ready for Review

#6971 Some fixes
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/HordeRaidEvent.java
  src/main/java/com/minecolonies/coremod/entity/CustomArrowEntity.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/EntityAIAttackArcher.java
Labels: PR: Hotfix, PR: Ready for Review

#6967 Multi fixes
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowRequestTree.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Hotfix, PR: Ready for Review

#6953 Added stone variants to pathblocks
  src/main/resources/data/minecolonies/tags/blocks/pathblocks.json
Labels: PR: Hotfix, PR: Ready for Review

#6969 Fix food interaction & food smelting
  src/api/java/com/minecolonies/api/colony/ICitizenData.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
Labels: PR: Hotfix, PR: Ready for Review

#6984 Misc schem, lang, etc fixes
  ABOUT.md
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/schematics/decorations/jungle/towncenter.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6990 Rescans the blackstone keep and fancy keep
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep1.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep2.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/blackstonekeep3.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep1.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep2.blueprint
  src/main/resources/assets/minecolonies/schematics/playerhousing/fancykeep3.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#6985 Expands turnoffExplosionsInColonies Setting
  src/api/java/com/minecolonies/api/colony/permissions/Explosions.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobKnight.java
  src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6998 fix cme
  src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java
Labels: PR: Hotfix, PR: Ready for Review

#7004 Have custom Recipes delegate reading of ItemStorage inputs to ItemStorage
  src/api/java/com/minecolonies/api/crafting/IImmutableItemStorageFactory.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/TypeConstants.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/crafting/ImmutableItemStorageFactory.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRecipeManager.java
  src/main/java/com/minecolonies/coremod/generation/CustomRecipeProvider.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7003 Fix stuckhandler not detecting unsuccessfull loops through timeouts
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Hotfix, PR: Ready for Review

#7002 Fix possible crash when setting blockstates
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: PR: Hotfix, PR: Ready for Review

#6999 Schem updates
  src/main/resources/assets/minecolonies/schematics/asian/archery5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/barracks5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/blacksmith3.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/blacksmith4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/blacksmith5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/combatacademy5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/cowboy1.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/cowboy2.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/cowboy3.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/cowboy4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/cowboy5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/enchanter4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/enchanter5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/fletcher3.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/fletcher4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/fletcher5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/guardtower5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/library4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/library5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite1.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/townhall4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/townhall5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/university5.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/warehouse4.blueprint
  src/main/resources/assets/minecolonies/schematics/asian/warehouse5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/archery5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/barracks5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/combatacademy5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/guardtower5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite2.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite3.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite4.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/mysticalsite5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/townhall5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/university5.blueprint
  src/main/resources/assets/minecolonies/schematics/caledonia/warehouse5.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/birch/largefield.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/university1.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/university2.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/university4.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#7000 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7006 ItemStorage fixes, Tooltips, Beekeeper_2 Research
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/researches/civilian/nightowl2.json
  src/main/generated/resources/data/minecolonies/researches/effects/beekeep2unlock.json
  src/main/generated/resources/data/minecolonies/researches/technology/honeypot.json
  src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutBeekeeperModule.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/beekeeper/BeekeeperSetHarvestHoneycombsMessage.java
  src/main/java/com/minecolonies/coremod/research/GlobalResearch.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7012 Improve food hand out
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
Labels: PR: Hotfix, PR: Ready for Review

#7017 Add breaking particles for graveyard
  src/main/resources/assets/minecolonies/models/block/blockhutgraveyard.json
Labels: PR: Hotfix, PR: Ready for Review

#7023 Fixes
  build.properties
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCowboy.java
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7026 Add missing breaking particles to buildings
  src/main/resources/assets/minecolonies/models/block/blockhutbaker.json
  src/main/resources/assets/minecolonies/models/block/blockhutmechanic.json
  src/main/resources/assets/minecolonies/models/block/blockhutmysticalsite.json
Labels: PR: Hotfix, PR: Ready for Review
