Repository ldtteam/minecolonies, pull requests merged in 2021-12, with the labels that each got.

#7819 Small fixes
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/StandardRequests.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
Labels: PR: Ready for Review, PR: Hotfix

#7824 Add waypoints for raiders
  src/api/java/com/minecolonies/api/colony/colonyEvents/IColonyRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/AbstractShipRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/HordeRaidEvent.java
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/pirateEvent/ShipBasedRaiderUtils.java
  src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderWalkAI.java
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7833 Better guard arrows
  src/main/java/com/minecolonies/coremod/entity/CustomArrowEntity.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/RangerCombatAI.java
Labels: PR: Ready for Review, PR: Hotfix

#7839 Mult fixes
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowWorkerModuleBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/trainingcamps/EntityAICombatTraining.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIVisitor.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review, PR: Hotfix

#7844 Add "universitylibrary" placement-helper blueprints for medieval styles
  src/main/resources/assets/minecolonies/schematics/decorations/medievalbirch/universitylibrary.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/medievaldarkoak/universitylibrary.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/medievaloak/universitylibrary.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/medievalspruce/universitylibrary.blueprint
Labels: PR: Ready for Review, PR: Schematics, PR: Hotfix

#7849 Fix supply loottable injection config
  src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java
  src/api/java/com/minecolonies/api/configuration/Configuration.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/loot/SupplyLoot.java
Labels: PR: Ready for Review, PR: Hotfix

#7842 Update smelter to be 1.17 aware
  src/api/java/com/minecolonies/api/colony/buildings/modules/ICraftingBuildingModule.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/items/ModTags.java
  src/api/java/com/minecolonies/api/util/constant/TagConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/requestable/SmeltableOre.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
  src/main/resources/data/minecolonies/tags/items/breakable_ore.json
  src/main/resources/data/minecolonies/tags/items/raw_ore.json
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday

#7845 Hut block as anchor in decoration
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutCrusherModule.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/FarmerFieldsModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/GraveyardManagementWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowHutMinerModule.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowMineGuardModule.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
Labels: PR: Ready for Review, PR: Hotfix

#7868 Add back in beige/cream/brown bricks
  src/main/resources/data/minecolonies/tags/blocks/pathblocks.json
Labels: PR: Ready for Review, PR: Hotfix

#7869 Fix tree search
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/ChunkCache.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobFindTree.java
Labels: PR: Ready for Review, PR: Hotfix

#7870 Fixes rendering of rack window
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowRack.java
Labels: PR: Ready for Review, PR: Hotfix

#7865 Clean compat dependencies in test environment
  gradle/dependencies.gradle
Labels: PR: Ready for Review, PR: Hotfix

#7872 Sev fixes
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowAssignCitizen.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/CourierAssignmentModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/BlockSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/AbstractEntityAIHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/Level.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/Node.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutblocksetting.xml
  src/main/resources/assets/minecolonies/lang/manual_en_us.json
Labels: PR: Ready for Review, PR: Hotfix

#7858 Journeymap integration
  gradle.properties
  gradle/configuration.gradle
  gradle/dependencies.gradle
  src/api/java/com/minecolonies/api/colony/event/AbstractColonyEvent.java
  src/api/java/com/minecolonies/api/colony/event/ClientChunkUpdatedEvent.java
  src/api/java/com/minecolonies/api/colony/event/ColonyViewUpdatedEvent.java
  src/api/java/com/minecolonies/api/colony/permissions/Action.java
  src/api/java/com/minecolonies/api/configuration/ClientConfiguration.java
  src/api/java/com/minecolonies/api/util/Utils.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/GraveManagerView.java
  src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java
  src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/ColonyBorderMapping.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/ColonyDeathpoints.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/Earcut.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/EventListener.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/JourneymapPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/PolygonUtils.java
  src/main/java/com/minecolonies/coremod/compatibility/journeymap/package-info.java
  src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java
  src/main/resources/META-INF/mods.toml
  src/main/resources/assets/minecolonies/lang/manual_en_us.json
  src/main/resources/assets/minecolonies/textures/icons/grave_icon.png
Labels: PR: Ready for Review, PR: Merge on Monday-Wednesday
