Repository ldtteam/minecolonies, pull requests merged in 2021-05, with the labels that each got.

#7053 Update NameConstants.java
  src/api/java/com/minecolonies/api/util/constant/NameConstants.java
Labels: PR: Hotfix, PR: Ready for Review

#7048 Small lang fix
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingChickenHerder.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
Labels: PR: Hotfix, PR: Ready for Review

#7042 Schem updates
  src/main/resources/assets/minecolonies/schematics/acacia/graveyard1.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/graveyard2.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/graveyard3.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/graveyard4.blueprint
  src/main/resources/assets/minecolonies/schematics/acacia/graveyard5.blueprint
  src/main/resources/assets/minecolonies/schematics/fortressalternative/university5.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/graveyard1.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/graveyard2.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/graveyard3.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/graveyard4.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/graveyard5.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/graveyard1.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/graveyard2.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/graveyard3.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/graveyard4.blueprint
  src/main/resources/assets/minecolonies/schematics/spacewars/graveyard5.blueprint
  src/main/resources/assets/minecolonies/schematics/supplycamp/asiansupplycamp.blueprint
Labels: PR: Hotfix, PR: Ready for Review, PR: Schematics

#7036 Fix some small grammar and spelling issues
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7047 Update delivery status when delivered in resource scroll
  src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java
Labels: PR: Hotfix, PR: Ready for Review, System: GUI

#7027 Handle removing used fuels from furnaces
  src/api/java/com/minecolonies/api/entity/ai/statemachine/states/AIWorkerState.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIUsesFurnace.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7040 Add a breeding setting to the apiary
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7031 Allow disabling sheep shearing
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkShepherd.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7029 Fix ItemStorage serialization, ensure that matching information persists in RecipeStorage
  src/api/java/com/minecolonies/api/crafting/IItemStorageFactory.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/java/com/minecolonies/coremod/colony/crafting/ItemStorageFactory.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7049 Constants cleanup
  src/api/java/com/minecolonies/api/util/constant/CommandConstants.java
  src/api/java/com/minecolonies/api/util/constant/Constants.java
  src/api/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/SchematicTagConstants.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/CommandClaimChunks.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7045 Improve hunger management
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
Labels: PR: Hotfix, PR: Ready for Review

#7058 Fix name generation for Eastern type names (fixes #7057)
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
Labels: PR: Hotfix, PR: Ready for Review

#6791 Enchanter loottable
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/ICompatibilityManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/crafting/IRecipeStorage.java
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
  src/main/generated/resources/data/minecolonies/crafterrecipes/enchanter/tome1.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/enchanter/tome2.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/enchanter/tome3.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/enchanter/tome4.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/enchanter/tome5.json
  src/main/generated/resources/data/minecolonies/loot_tables/recipes/enchanter1.json
  src/main/generated/resources/data/minecolonies/loot_tables/recipes/enchanter2.json
  src/main/generated/resources/data/minecolonies/loot_tables/recipes/enchanter3.json
  src/main/generated/resources/data/minecolonies/loot_tables/recipes/enchanter4.json
  src/main/generated/resources/data/minecolonies/loot_tables/recipes/enchanter5.json
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/enchanter/EntityAIWorkEnchanter.java
  src/main/java/com/minecolonies/coremod/event/GatherDataHandler.java
  src/main/java/com/minecolonies/coremod/generation/CustomRecipeProvider.java
  src/main/java/com/minecolonies/coremod/generation/LootTableBuilder.java
  src/main/java/com/minecolonies/coremod/generation/LootTableJsonProvider.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultEnchanterCraftingProvider.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultSifterCraftingProvider.java
  src/main/java/com/minecolonies/coremod/generation/defaults/SawmillTimberFrameRecipeProvider.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7064 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7066 Recover the colony relationship for colony flags placed by the builder that are stuck "white"
  src/api/java/com/minecolonies/api/blocks/decorative/AbstractColonyFlagBanner.java
  src/api/java/com/minecolonies/api/tileentities/TileEntityColonyFlag.java
Labels: PR: Hotfix, PR: Ready for Review

#7074 fix small gui npe
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHallColonyManage.java
Labels: PR: Hotfix, PR: Ready for Review

#7068 Make Zombie Villagers convert to Visitors in colonies with Taverns
  src/api/java/com/minecolonies/api/util/constant/Constants.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/TavernBuildingModule.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7077 Fix grave CME
  src/api/java/com/minecolonies/api/colony/managers/interfaces/IGraveManager.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java
  src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java
Labels: PR: Hotfix, PR: Ready for Review

#7086 Prevent jumping at fence gates
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/MovementHandler.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7088 Properly cleanup requests
  src/api/java/com/minecolonies/api/colony/requestsystem/management/IRequestHandler.java
  src/api/java/com/minecolonies/api/colony/requestsystem/manager/IRequestManager.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobDeliveryman.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/wrapped/AbstractWrappedRequestManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
Labels: PR: Hotfix, PR: Ready for Review

#7070 Fix smelter fuel retaining to not be coal greedy
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingFurnaceUser.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGlassblower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
Labels: PR: Hotfix, PR: Ready for Review

#7092 Prevent citizens from eating glass bottles
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
Labels: PR: Hotfix, PR: Ready for Review

#7096 Soul recipes
  src/main/resources/data/minecolonies/crafterrecipes/mechanic/soul_lantern.json
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
Labels: PR: Hotfix, PR: Ready for Review

#7093 Fix npe in unReserveGrave
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java
  src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java
Labels: PR: Hotfix, PR: Ready for Review

#7097 Several fixes
  build.gradle
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingArchery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRandomPos.java
  src/main/java/com/minecolonies/coremod/event/EventHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPlaceMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/DirectPlaceMessage.java
  src/main/resources/data/minecolonies/tags/blocks/decoblocks.json
Labels: PR: Hotfix, PR: Ready for Review

#7098 Display child's name in the new child message
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/LivingBuildingModule.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7104 fix 7103
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java
Labels: PR: Hotfix, PR: Ready for Review

#7101 Add correct handling of resolver cancellation
  src/api/java/com/minecolonies/api/colony/requestsystem/management/IResolverHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/ProviderHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/ResolverHandler.java
Labels: PR: Hotfix, PR: Ready for Review

#7079 finish the tree stuff
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
  src/api/java/com/minecolonies/api/util/InventoryUtils.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutLumberjackModule.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobFindTree.java
  src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/GuardScepterMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/beekeeper/BeekeeperScepterMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/lumberjack/LumberjackScepterMessage.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutfilterablelist.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, Port to PVI, System: GUI, System: Pathfinding

#7112 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7099 Totem of Undying functionality and research for Undertaker
  src/api/java/com/minecolonies/api/advancements/AdvancementTriggers.java
  src/api/java/com/minecolonies/api/advancements/undertaker_totem/UndertakerTotemCriterionInstance.java
  src/api/java/com/minecolonies/api/advancements/undertaker_totem/UndertakerTotemTrigger.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/api/java/com/minecolonies/api/util/constant/Constants.java
  src/api/java/com/minecolonies/api/util/constant/UndertakerConstants.java
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/researches/civilian/raisingthedead.json
  src/main/generated/resources/data/minecolonies/researches/effects/usetotemunlock.json
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/advancements/minecolonies/undertaker_totem.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7118 fix issue 7117
  src/api/java/com/minecolonies/api/blocks/AbstractBlockMinecoloniesRack.java
  src/api/java/com/minecolonies/api/blocks/types/RackType.java
  src/api/java/com/minecolonies/api/colony/IColony.java
  src/api/java/com/minecolonies/api/entity/CustomGoalSelector.java
  src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/BedHandlingModule.java
  src/main/java/com/minecolonies/coremod/placementhandlers/DimensionFluidHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7113 Remove redundant recipes.
  src/main/resources/data/minecolonies/crafterrecipes/sifter/dirt.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/gravel.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/sand.json
  src/main/resources/data/minecolonies/crafterrecipes/sifter/soul_sand.json
Labels: PR: Hotfix, PR: Ready for Review

#7091 Don't require items for recruiting visitors on creative mode
  src/main/java/com/minecolonies/coremod/colony/interactionhandling/RecruitmentInteraction.java
Labels: PR: Hotfix, PR: Ready for Review

#7124 Add hint to beekeeper no hive message
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7132 Fix 7131
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFarmer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java
Labels: PR: Hotfix, PR: Ready for Review

#7089 Create reset to default button in the item list module
  src/api/java/com/minecolonies/api/colony/buildings/modules/IItemListModuleView.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/ItemListModuleWindow.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/ItemListModuleView.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutfilterablelist.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, System: GUI

#7140 Add honey and honeycomb blocks to mechanic repertoire
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
Labels: PR: Hotfix, PR: Ready for Review

#7139 Recipe/concrete glass
  src/main/generated/resources/assets/minecolonies/lang/default.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/black_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/black_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/blue_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/blue_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/brown_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/brown_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/cyan_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/cyan_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/gray_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/gray_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/green_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/green_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/light_blue_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/light_blue_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/light_gray_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/light_gray_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/lime_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/lime_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/magenta_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/magenta_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/orange_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/orange_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/pink_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/pink_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/purple_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/purple_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/red_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/red_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/white_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/white_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/yellow_concrete.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/concretemixer/yellow_concrete_powder.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/glassblower/red_sand.json
  src/main/generated/resources/data/minecolonies/crafterrecipes/glassblower/sand.json
  src/main/generated/resources/data/minecolonies/researches/civilian/raisingthedead.json
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingConcreteMixer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGlassblower.java
  src/main/java/com/minecolonies/coremod/event/GatherDataHandler.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultConcreteMixerCraftingProvider.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultGlassblowerCraftingProvider.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#6855 Add custom ranks
  src/api/java/com/minecolonies/api/colony/IColonyView.java
  src/api/java/com/minecolonies/api/colony/permissions/IPermissions.java
  src/api/java/com/minecolonies/api/colony/permissions/OldRank.java
  src/api/java/com/minecolonies/api/colony/permissions/Rank.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java
  src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java
  src/main/java/com/minecolonies/coremod/colony/pvp/AttackingPlayer.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/CommandAddOfficer.java
  src/main/java/com/minecolonies/coremod/commands/colonycommands/CommandSetAbandoned.java
  src/main/java/com/minecolonies/coremod/commands/commandTypes/IMCColonyOfficerCommand.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/PermissionsMessage.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/TeleportToColonyMessage.java
  src/main/java/com/minecolonies/coremod/util/AdvancementUtils.java
  src/main/resources/assets/minecolonies/gui/townhall/layoutpermissions.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7150 Send citizen cap progress message when reaching the actual cap
  src/api/java/com/minecolonies/api/colony/ColonyProgressType.java
  src/main/java/com/minecolonies/coremod/colony/managers/ProgressManager.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7147 Add int setting and leftover request handling to warehouse
  build.properties
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/IIntSettingFactory.java
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/INonExhaustiveDeliverable.java
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/StackList.java
  src/api/java/com/minecolonies/api/tileentities/AbstractTileEntityWareHouse.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/IntSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingComposter.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseConcreteRequestResolver.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractWarehouseRequestResolver.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java
  src/main/resources/META-INF/mods.toml
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutintsetting.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7153 Add tinker's compatibility
  build.gradle
  build.properties
  src/api/java/com/minecolonies/api/compatibility/tinkers/SlimeTreeCheck.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersWeaponHelper.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/ToolBrokenCheck.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7151 Also switch plantation to module setting
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/IStringSetting.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutPlantationModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/PlantationSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/StringSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/network/NetworkChannel.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/plantation/PlantationSetPhaseMessage.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7163 Fix tinker's compat
  src/api/java/com/minecolonies/api/compatibility/Compatibility.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/SlimeTreeProxy.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersToolHelper.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersToolProxy.java
  src/api/java/com/minecolonies/api/compatibility/tinkers/ToolBrokenCheck.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
Labels: PR: Hotfix, PR: Ready for Review

#7171 Add dynamic trees compat
  build.gradle
  build.properties
  src/api/java/com/minecolonies/api/compatibility/Compatibility.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/compatibility/dynamictrees/DynamicTreeCompat.java
  src/api/java/com/minecolonies/api/compatibility/dynamictrees/DynamicTreeProxy.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7173 Bump structurize
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7172 Fix hiring from archery/combat academy
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingArchery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
Labels: PR: Hotfix, PR: Ready for Review

#7162 Builder resource list view module
  src/api/java/com/minecolonies/api/util/constant/WindowConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowAssignCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutBuilderModule.java
  src/main/java/com/minecolonies/coremod/client/gui/huts/WindowHutWareHouse.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/WindowBuilderResModule.java
  src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowTownHall.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/BuildingResourcesModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/CrafterTaskModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/BuildingResourcesModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingBuilderView.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/event/ClientEventHandler.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/TransferItemsRequestMessage.java
  src/main/resources/assets/minecolonies/gui/layouthuts/layoutbuilderres.xml
  src/main/resources/assets/minecolonies/gui/windowhutbuilder.xml
  src/main/resources/assets/minecolonies/gui/windowhutdeliveryman.xml
  src/main/resources/assets/minecolonies/gui/windowhutglassblower.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, System: GUI

#7177 Update some config defaults
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
Labels: PR: Hotfix, PR: Ready for Review

#7166 Allow fletcher to craft things from rabbit hides
  src/main/resources/data/minecolonies/tags/items/fletcher_ingredient.json
  src/main/resources/data/minecolonies/tags/items/fletcher_product_excluded.json
Labels: PR: Hotfix, PR: Ready for Review

#7178 Remove tool smelting
  src/api/java/com/minecolonies/api/entity/ai/statemachine/states/AIWorkerState.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review
