Repository ldtteam/minecolonies, pull requests merged in 2021-01, with the labels that each got.

#6386 Cook and mechanic can craft dried kelp blocks
  src/main/resources/data/minecolonies/tags/items/cook_ingredient.json
  src/main/resources/data/minecolonies/tags/items/mechanic_ingredient.json
  src/main/resources/data/minecolonies/tags/items/mechanic_product.json
Labels: PR: Ready For Review, System: Request System

#6387 Changes cure to honey bottles instead of honey combs
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
Labels: PR: Ready For Review

#6392 Add quartz bricks to stonemason product
  src/main/resources/data/minecolonies/tags/items/stonemason_product.json
Labels: PR: Ready For Review, System: Request System

#6393 Add campfires to the deco phase
  src/main/resources/data/minecolonies/tags/blocks/decoblocks.json
Labels: PR: Ready For Review

#6408 Bug Squashes, Eastern Name Order, Gender Issues, and ItemTagResolver Display Tweaks
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/util/ItemStackUtils.java
  src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowRequestTree.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/StandardRequests.java
  src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/models/block/blockhutchickenherder.json
  src/main/resources/assets/minecolonies/models/block/blockhutdeliveryman.json
  src/main/resources/assets/minecolonies/models/block/blockhutshepherd.json
  src/main/resources/assets/minecolonies/models/block/blockhutwarehouse.json
Labels: PR: Ready For Review

#6385 Bump structurize 1.15
  build.properties
  src/main/resources/META-INF/mods.toml
Labels: 1.15, PR: Ready for Review, Related: Structurize

#6413 Add new patreon's name to the list of citizen names
  src/api/java/com/minecolonies/api/util/constant/NameConstants.java
Labels: PR: Ready for Review

#6397 Damage -> Injuries
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6414 Feature/student hiring
  src/api/java/com/minecolonies/api/colony/buildings/IBuildingCanBeHiredFrom.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingArchery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLibrary.java
Labels: PR: Ready for Review

#6360 Happiness tweaks
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenHappinessHandler.java
Labels: PR: Ready for Review

#6321 Scroll messages and other lang fixes
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6405 Edits github-only files
  ABOUT.md
  CLA.md
  README.md
  minecolonies.png
  resources/minecolonies.png
  src/main/resources/META-INF/mods.toml
  src/main/resources/minecolonies.png
Labels: PR: Ready for Review

#6450 More fortress deco
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/mushroomfarm.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction3.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/fortress/moatcornernether.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/fortress/moatinnercornercobble.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/fortress/moatinnercornernether.blueprint
  src/main/resources/assets/minecolonies/schematics/walls/fortress/moatinnercornerstone.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6462 Pirate fix
  src/main/resources/assets/minecolonies/schematics/ships/big_pirate_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/medium_pirate_ship.blueprint
  src/main/resources/assets/minecolonies/schematics/ships/small_pirate_ship.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics
