Repository ldtteam/minecolonies, pull requests merged in 2021-02, with the labels that each got.

#6467 More lang fixes and dead code removal
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBlacksmith.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingConcreteMixer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFarmer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFletcher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMechanic.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStoneSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSwineHerder.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/baker/EntityAIWorkBaker.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/fisherman/EntityAIWorkFisherman.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkRabbitHerder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/planter/EntityAIWorkPlanter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/school/EntityAIWorkTeacher.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
  src/main/resources/assets/minecolonies/gui/townhall/windowtownhallhirecitizen.xml
  src/main/resources/assets/minecolonies/gui/windowbuilldtool.xml
  src/main/resources/assets/minecolonies/gui/windowmultiblock.xml
  src/main/resources/assets/minecolonies/gui/windowscantool.xml
  src/main/resources/assets/minecolonies/gui/windowstructurenameentry.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6469 Add palette-swaps of the medieval small stable.
  src/main/resources/assets/minecolonies/schematics/decorations/medievalbirch/small_stable.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/medievalspruce/small_stable.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6541 Improve compatibility with modded farmland blocks.
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java
Labels: Compatibility: Mod, PR: Ready for Review

#6530 Lets blacksmith craft netherite items
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_axe.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_boots.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_chestplate.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_helmet.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_hoe.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_leggings.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_pickaxe.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_shovel.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/netherite_sword.json
Labels: Compatibility: Vanilla, PR: Ready for Review

#6528 Schematic fixes
  src/main/resources/assets/minecolonies/schematics/asianalterantive/citizen1.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/citizen2.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/citizen3.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/citizen4.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/citizen5.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/guardtower1.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/guardtower2.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/guardtower3.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/guardtower4.blueprint
  src/main/resources/assets/minecolonies/schematics/asianalterantive/guardtower5.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/bathhouse1.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/bathhouse2.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/asian/bathhouse3.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpfarm.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpfarmcombo.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpfarmdual.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpsmoked.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpsmokeddual.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/mushroomfarm.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/stonemason3.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/stonemason4.blueprint
  src/main/resources/assets/minecolonies/schematics/jungle/stonemason5.blueprint
  src/main/resources/assets/minecolonies/schematics/medievaloak/dyer1.blueprint
  src/main/resources/assets/minecolonies/schematics/medievaloak/dyer2.blueprint
  src/main/resources/assets/minecolonies/schematics/medievaloak/dyer3.blueprint
  src/main/resources/assets/minecolonies/schematics/medievaloak/dyer4.blueprint
  src/main/resources/assets/minecolonies/schematics/medievaloak/dyer5.blueprint
  src/main/resources/assets/minecolonies/schematics/mesa/stonemason3.blueprint
  src/main/resources/assets/minecolonies/schematics/mesa/stonemason4.blueprint
  src/main/resources/assets/minecolonies/schematics/mesa/stonemason5.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/footpathhosp.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/footpathuni.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/minipath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/minipath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/minipath3.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6518 fix #6513
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
Labels: PR: Ready for Review

#6532 Fix botania compat with florist
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/items/ModTags.java
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/data/minecolonies/tags/items/florist_flowers_excluded.json
Labels: Compatibility: Mod, PR: Ready for Review

#6521 More immersive message and config fixes
  ABOUT.md
  src/api/java/com/minecolonies/api/configuration/ClientConfiguration.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java
  src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6554 Draxx's deco changes
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpfarmdual.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpsmoked.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/kelpsmokeddual.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corner3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corneralt1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corneralt2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/corneralt3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/footpath.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/longpath3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/minipath3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction3.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6552 More schem fixes
  src/main/resources/assets/minecolonies/schematics/fields/fortress/fortressfarma.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/fortressfarmb.blueprint
  src/main/resources/assets/minecolonies/schematics/fields/fortress/fortressfarmc.blueprint
  src/main/resources/assets/minecolonies/schematics/infrastructure/basicbridge.blueprint
  src/main/resources/assets/minecolonies/schematics/infrastructure/oakbridgespan.blueprint
  src/main/resources/assets/minecolonies/schematics/infrastructure/oakbridgestairs.blueprint
  src/main/resources/assets/minecolonies/schematics/infrastructure/patrolpoint.blueprint
  src/main/resources/assets/minecolonies/schematics/supplyship/spacewarsupplyship.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6551 Building Modules
  src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/AbstractBuildingModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IBuildingModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IBuildingModuleProvider.java
  src/api/java/com/minecolonies/api/colony/buildings/registry/BuildingEntry.java
  src/api/java/com/minecolonies/api/entity/ai/pathfinding/AbstractWalkToProxy.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutCitizen.java
  src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTavern.java
  src/main/java/com/minecolonies/coremod/colony/buildings/DefaultBuildingInstance.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/BedHandlingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/HomeBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/LivingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/TavernBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/registry/BuildingDataManager.java
  src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java
  src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/util/TeleportHelper.java
Labels: PR: Ready for Review

#6529 More sifter improvements
  src/api/java/com/minecolonies/api/crafting/ClassicRecipe.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutSifter.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/sifter/EntityAIWorkSifter.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6574 Cleanup mourning
  src/api/java/com/minecolonies/api/entity/ai/statemachine/tickratestatemachine/TickingTransition.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIMournCitizen.java
Labels: PR: Ready for Review

#6580 Fortress deco updates
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal1.blueprint
  src/main/resources/assets/minecolonies/schematics/decorations/fortress/netherportal2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/footpathhosp.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/intersection3.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath1.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/shortpath2.blueprint
  src/main/resources/assets/minecolonies/schematics/roads/fortress/tjunction3.blueprint
Labels: 1.16, PR: Ready for Review, PR: Schematics

#6570 Several Improvements
  src/api/java/com/minecolonies/api/colony/buildings/IBuildingBedProvider.java
  src/api/java/com/minecolonies/api/colony/buildings/IWorkerLivingBuilding.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingArchery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCombatAcademy.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/trainingcamps/EntityAICombatTraining.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAISleep.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/placementhandlers/RackPlacementHandler.java
  src/main/resources/assets/minecolonies/gui/windowhireworker.xml
Labels: PR: Ready for Review

#6582 Serveral fixes
  src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/api/java/com/minecolonies/api/util/constant/ColonyManagerConstants.java
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCrafting.java
  src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIInteractToggleAble.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollBuff.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollColonyAreaTP.java
  src/main/java/com/minecolonies/coremod/items/ItemScrollColonyTP.java
  src/main/java/com/minecolonies/coremod/util/BackUpHelper.java
Labels: PR: Ready for Review

#6498 Food tweaks
  src/api/java/com/minecolonies/api/colony/ICitizenData.java
  src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java
  src/api/java/com/minecolonies/api/util/constant/CitizenConstants.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowHutCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/StandardRequests.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/resources/assets/minecolonies/gui/citizen/main.xml
  src/main/resources/assets/minecolonies/gui/windowhutcook.xml
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6600 Blueprint rendering config option
  src/api/java/com/minecolonies/api/configuration/ClientConfiguration.java
  src/main/java/com/minecolonies/coremod/event/ClientEventHandler.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6594 Chunkloading/set blockstate fixes
  src/api/java/com/minecolonies/api/colony/IColony.java
  src/api/java/com/minecolonies/api/colony/managers/interfaces/IBuildingManager.java
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/util/WorldUtil.java
  src/main/java/com/minecolonies/coremod/colony/Colony.java
  src/main/java/com/minecolonies/coremod/colony/ColonyView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/interactionhandling/PosBasedInteraction.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIInteractToggleAble.java
  src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenItemHandler.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/ChunkCache.java
  src/main/java/com/minecolonies/coremod/event/DebugRendererChunkBorder.java
  src/main/java/com/minecolonies/coremod/util/ChunkDataHelper.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6597 Improve food pick up
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
Labels: PR: Ready for Review

#6578 Update for new Structurize bricks
  src/main/resources/data/minecolonies/tags/blocks/pathblocks.json
  src/main/resources/data/minecolonies/tags/items/stonemason_ingredient.json
Labels: PR: Ready for Review

#6601 Add config option to disable supply loot
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/main/java/com/minecolonies/coremod/loot/SupplyLoot.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Ready for Review

#6619 Reduce dietary iron.
  src/api/java/com/minecolonies/api/crafting/RecipeStorage.java
Labels: PR: Ready for Review

#6606 Add a special medieval armor that only the blacksmith can create
  src/api/java/com/minecolonies/api/configuration/ServerConfiguration.java
  src/api/java/com/minecolonies/api/items/ModItems.java
  src/api/java/com/minecolonies/api/research/util/ResearchConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModItemsInitializer.java
  src/main/java/com/minecolonies/coremod/items/ItemPlateArmor.java
  src/main/java/com/minecolonies/coremod/research/ResearchInitializer.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/models/item/plate_armor_boots.json
  src/main/resources/assets/minecolonies/models/item/plate_armor_chest.json
  src/main/resources/assets/minecolonies/models/item/plate_armor_helmet.json
  src/main/resources/assets/minecolonies/models/item/plate_armor_legs.json
  src/main/resources/assets/minecolonies/textures/items/plate_armor_boots.png
  src/main/resources/assets/minecolonies/textures/items/plate_armor_chest.png
  src/main/resources/assets/minecolonies/textures/items/plate_armor_helmet.png
  src/main/resources/assets/minecolonies/textures/items/plate_armor_legs.png
  src/main/resources/assets/minecolonies/textures/models/armor/plate_armor_layer_1.png
  src/main/resources/assets/minecolonies/textures/models/armor/plate_armor_layer_2.png
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/platearmorboots.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/platearmorchestplate.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/platearmorhelmet.json
  src/main/resources/data/minecolonies/crafterrecipes/blacksmith/platearmorlegs.json
Labels: PR: Ready for Review

#6608 Adjust builder positioning to pathfinding from random pos
  src/api/java/com/minecolonies/api/entity/pathfinding/AbstractAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobRandomPos.java
Labels: PR: Ready for Review

#6605 Fix tags
  src/main/resources/data/minecolonies/tags/blocks/pathblocks.json
  src/main/resources/data/minecolonies/tags/items/florist_flowers_excluded.json
Labels: PR: Ready for Review

#6614 Fixes some models and textures
  README.md
  src/main/resources/assets/minecolonies/models/block/blockhutchickenherder.json
  src/main/resources/assets/minecolonies/models/block/blockhutcomposter.json
  src/main/resources/assets/minecolonies/models/block/blockhutconcretemixer.json
  src/main/resources/assets/minecolonies/models/block/blockhutdeliveryman.json
  src/main/resources/assets/minecolonies/models/block/blockhutenchanter.json
  src/main/resources/assets/minecolonies/models/block/blockhutglassblower.json
  src/main/resources/assets/minecolonies/models/block/blockhuthospital.json
  src/main/resources/assets/minecolonies/models/block/blockhutschool.json
  src/main/resources/assets/minecolonies/models/block/blockhutshepherd.json
  src/main/resources/assets/minecolonies/models/block/blockhutuniversity.json
  src/main/resources/assets/minecolonies/models/block/blockhutwarehouse.json
  src/main/resources/assets/minecolonies/textures/blocks/bookshelf.png
  src/main/resources/assets/minecolonies/textures/blocks/enchanting_table_bottom.png
  src/main/resources/assets/minecolonies/textures/blocks/enchanting_table_side.png
  src/main/resources/assets/minecolonies/textures/blocks/enchanting_table_top.png
  src/main/resources/assets/minecolonies/textures/blocks/liquid/liq1.png
  src/main/resources/assets/minecolonies/textures/blocks/planks_oak.png
  src/main/resources/assets/minecolonies/textures/blocks/university/tableside.png
Labels: PR: Ready for Review

#6610 Some fixes
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIInteractToggleAble.java
Labels: PR: Ready for Review

#6624 Townhall sorting
  src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java
Labels: PR: Ready for Review
