Repository ldtteam/minecolonies, pull requests merged in 2021-06, with the labels that each got.

#7192 fix 7186
  src/api/java/com/minecolonies/api/entity/pathfinding/AbstractAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/herders/EntityAIWorkCowboy.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobFindTree.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7189 Made it so that citizens that work in a building are always at the to…
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
Labels: Minor, PR: Hotfix, PR: Ready for Review

#7195 Some code improvements.
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/ItemListModule.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java
Labels: PR: Hotfix, PR: Ready for Review

#7174 Add minimum stock to more buildings
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7181 Allow players to set the flowers the beekeeper feeds to his bees
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/util/InventoryUtils.java
  src/api/java/com/minecolonies/api/util/constant/BuildingConstants.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/FloristFlowerListModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBeekeeper.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/beekeeper/EntityAIWorkBeekeeper.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7204 fix#7198
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/core/AbstractCraftingRequestResolver.java
Labels: PR: Hotfix, PR: Ready for Review

#7149 JEI crafting integration, redux
  build.gradle
  build.properties
  src/api/java/com/minecolonies/api/colony/buildings/IBuildingWorker.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/IBuildingModuleView.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/ICraftingBuildingModule.java
  src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
  src/api/java/com/minecolonies/api/crafting/GenericRecipe.java
  src/api/java/com/minecolonies/api/crafting/IGenericRecipe.java
  src/api/java/com/minecolonies/api/crafting/ItemStorage.java
  src/api/java/com/minecolonies/api/util/CraftingUtils.java
  src/api/java/com/minecolonies/api/util/constant/TagConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModTagsInitializer.java
  src/main/java/com/minecolonies/coremod/client/gui/AbstractModuleWindow.java
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCrafting.java
  src/main/java/com/minecolonies/coremod/client/gui/containers/WindowFurnaceCrafting.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/SimpleCraftingModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/moduleviews/CraftingModuleView.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBaker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBlacksmith.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingConcreteMixer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingDyer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingEnchanter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFarmer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFletcher.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGlassblower.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMechanic.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSifter.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStoneSmeltery.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipe.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipeManager.java
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipesReloadedEvent.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeUtils.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JobBasedRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/LootTableAnalyzer.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/RenderHelper.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/package-info.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/AbstractTeachingGuiHandler.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/CraftingGuiHandler.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/transfer/FurnaceCraftingGuiHandler.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
  src/main/java/com/minecolonies/coremod/util/FurnaceRecipes.java
  src/main/resources/assets/minecolonies/lang/en_us.json
  src/main/resources/assets/minecolonies/textures/gui/jei_recipe.png
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7209 Fix oopsy
  src/api/java/com/minecolonies/api/colony/buildings/IGuardBuilding.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/ISettingsModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/ISetting.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/IStringSetting.java
  src/api/java/com/minecolonies/api/colony/guardtype/GuardType.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/apiimp/initializer/ModGuardTypesInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingGuards.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/SettingsModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/GuardJobSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/GuardTaskSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/SettingsFactories.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/StringSetting.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/TriggerSettingMessage.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review, System: GUI

#7215 Ignore some weird or invalid recipes added by other mods
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeUtils.java
Labels: PR: Hotfix, PR: Ready for Review

#7202 Fix builder job start message typo
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Hotfix, PR: Ready for Review

#7224 Fix JEI datapack loot, kinda
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
Labels: PR: Hotfix, PR: Ready for Review

#7246 Fixes
  src/api/java/com/minecolonies/api/colony/buildings/modules/ISettingsModule.java
  src/api/java/com/minecolonies/api/colony/buildings/modules/settings/ISetting.java
  src/main/java/com/minecolonies/coremod/client/gui/modules/MinimumStockModuleWindow.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/SettingsModule.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/GuardJobSetting.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/GuardTaskSetting.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/composter/EntityAIWorkComposter.java
  src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/TriggerSettingMessage.java
Labels: PR: Hotfix, PR: Ready for Review

#7248 Compatibility with JustEnoughResources
  src/main/java/com/minecolonies/coremod/compatibility/jei/JEIPlugin.java
Labels: PR: Hotfix, PR: Ready for Review

#7259 Fix tinker's compat
  build.properties
  src/api/java/com/minecolonies/api/compatibility/tinkers/TinkersToolHelper.java
Labels: PR: Hotfix, PR: Ready for Review

#7265 Fix research effect tooltip duplication
  src/main/java/com/minecolonies/coremod/research/GlobalResearchTree.java
Labels: PR: Hotfix, PR: Ready for Review

#7264 Calculate loot drops on server side for JEI integration
  src/main/java/com/minecolonies/coremod/colony/crafting/CustomRecipeManager.java
  src/main/java/com/minecolonies/coremod/colony/crafting/LootTableAnalyzer.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/GenericRecipeCategory.java
  src/main/java/com/minecolonies/coremod/compatibility/jei/JobBasedRecipeCategory.java
  src/main/java/com/minecolonies/coremod/datalistener/CrafterRecipeListener.java
Labels: PR: Hotfix, PR: Ready for Review

#7263 Prevent portal travel
  src/api/java/com/minecolonies/api/entity/citizen/AbstractCivilianEntity.java
  src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java
  src/api/java/com/minecolonies/api/entity/mobs/AbstractEntityMinecoloniesMob.java
Labels: PR: Hotfix, PR: Ready for Review

#7258 [HotFix] Fix miners using default blockstate tool instead of real blockstate tool.
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/florist/EntityAIWorkFlorist.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/planter/EntityAIWorkPlanter.java
  src/main/java/com/minecolonies/coremod/util/WorkerUtil.java
Labels: PR: Hotfix, PR: Ready for Review

#7234 Add alt materials + add ocean plant allowance.
  src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/pirateEvent/ShipBasedRaiderUtils.java
Labels: PR: Hotfix, PR: Ready for Review

#7266 fix 7184
  src/api/java/com/minecolonies/api/util/BlockPosUtil.java
Labels: PR: Hotfix, PR: Ready for Review

#7273 Add some null checks while persisting permissions
  src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java
Labels: PR: Hotfix, PR: Ready for Review

#7270 fix 7146
  src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowRequestDetail.java
  src/main/java/com/minecolonies/coremod/items/ItemPharaoScepter.java
Labels: PR: Hotfix, PR: Ready for Review

#7255 Barracks Minimum Stock + Crafting Tweaks
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingBarracks.java
  src/main/resources/data/minecolonies/tags/items/blacksmith_ingredient.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7283 Update undertaker models and textures
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityUndertaker.java
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityUndertakerFemale.java
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityUndertakerMale.java
  src/main/java/com/minecolonies/coremod/client/render/modeltype/registry/ModelTypeRegistry.java
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakerfemale1_a.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakerfemale1_b.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakerfemale1_d.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakerfemale1_w.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakermale1_a.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakermale1_b.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakermale1_d.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/default/undertakermale1_w.png
Labels: PR: Hotfix, PR: Ready for Review

#7290 Setup iterator type correctly - bump structurize
  build.properties
  src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java
  src/main/java/com/minecolonies/coremod/client/gui/WindowBuildDecoration.java
  src/main/java/com/minecolonies/coremod/colony/workorders/AbstractWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/resources/META-INF/mods.toml
Labels: PR: Hotfix, PR: Ready for Review

#7303 Undertaker model fix & Medieval textures
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityUndertakerFemale.java
  src/main/java/com/minecolonies/coremod/client/model/ModelEntityUndertakerMale.java
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakerfemale1_a.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakerfemale1_b.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakerfemale1_d.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakerfemale1_w.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakermale1_a.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakermale1_b.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakermale1_d.png
  src/main/resources/assets/minecolonies/textures/entity/citizen/medieval/undertakermale1_w.png
Labels: PR: Hotfix, PR: Ready for Review

#7037 Add mercenary sound events and sounds
  src/api/java/com/minecolonies/api/sounds/MercenarySounds.java
  src/api/java/com/minecolonies/api/sounds/ModSoundEvents.java
  src/main/generated/resources/assets/minecolonies/sounds.json
  src/main/java/com/minecolonies/coremod/entity/mobs/EntityMercenary.java
  src/main/java/com/minecolonies/coremod/entity/mobs/EntityMercenaryAI.java
  src/main/java/com/minecolonies/coremod/generation/defaults/DefaultSoundProvider.java
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/attack/attack1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/attack/attack2.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/attack/attack3.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/attack/attack4.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/celebrate/celebrate1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/die/death1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/die/death2.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/hurt/hurt1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/hurt/hurt2.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/hurt/hurt3.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/say/say1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/say/say2.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/say/say3.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/step/step1.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/step/step2.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/step/step3.ogg
  src/main/resources/assets/minecolonies/sounds/mob/mercenary/step/step4.ogg
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7313 Solve trapdoor pathing
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobFindTree.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/PathJobMoveToWithPassable.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7301 Fix citizens sometimes spinning
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7300 Raid starting difficulty adjustment/remove hutblock schems
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/archeryhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/bakerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/barrackshut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/barrackstowerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/beekeeperhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/blacksmithhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/builderhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/chickenherderhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/combatacademyhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/composterhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/concretemixerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/cookhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/cowboyhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/crusherhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/deliverymanhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/dyerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/enchanterhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/farmerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/fishermanhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/fletcherhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/floristhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/glassblowerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/graveyardhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/guardtowerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/homehut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/hospitalhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/libraryhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/lumberjackhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/mechanichut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/minerhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/mysticalsitehut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/plantationhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/postboxhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/rabbithutchhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/sawmillhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/schoolhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/shepherdhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/sifterhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/smelteryhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/stashhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/stonemasonhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/stonesmelteryhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/swineherderhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/tavernhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/townhallhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/universityhut.blueprint
  src/main/generated/resources/assets/minecolonies/schematics/infrastructure/hutblocks/warehousehut.blueprint
  src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java
  src/main/java/com/minecolonies/coremod/event/GatherDataHandler.java
  src/main/java/com/minecolonies/coremod/generation/defaults/HutBlockSchematicProvider.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review, PR: Schematics

#7274 Move active handling to citizenData
  src/api/java/com/minecolonies/api/colony/ICitizenData.java
  src/api/java/com/minecolonies/api/colony/jobs/IJob.java
  src/api/java/com/minecolonies/api/util/constant/CitizenConstants.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
  src/main/java/com/minecolonies/coremod/colony/jobs/JobDeliveryman.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliverymenRequestResolver.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAISickTask.java
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7296 Fix completition message, furnace issue and resourcelist display
  src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingFurnaceUser.java
  src/main/java/com/minecolonies/coremod/colony/workorders/AbstractWorkOrder.java
  src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7318 Fix server-side module views
  src/api/java/com/minecolonies/api/colony/buildings/registry/BuildingEntry.java
  src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java
Labels: PR: Hotfix, PR: Ready for Review

#7315 Add Rain and Raid interaction
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java
  src/main/resources/assets/minecolonies/lang/en_us.json
Labels: PR: Merge on Monday-Wednesday, PR: Ready for Review

#7317 fix pathing
  src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java
Labels: PR: Hotfix, PR: Ready for Review, System: Pathfinding

#7324 private crafting hotfix
  src/api/java/com/minecolonies/api/colony/buildings/modules/ICraftingBuildingModule.java
  src/api/java/com/minecolonies/api/crafting/IRecipeManager.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java
  src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRecipeManager.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/PrivateWorkerCraftingProductionResolver.java
Labels: PR: Hotfix, PR: Ready for Review

#7310 Several miner fixes
  src/api/java/com/minecolonies/api/entity/ai/statemachine/states/AIWorkerState.java
  src/api/java/com/minecolonies/api/tileentities/AbstractTileEntityColonyBuilding.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingContainer.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java
  src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java
  src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java
  src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/Level.java
  src/main/java/com/minecolonies/coremod/entity/ai/citizen/planter/EntityAIWorkPlanter.java
  src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java
  src/main/java/com/minecolonies/coremod/entity/pathfinding/EntityCitizenWalkToProxy.java
  src/main/java/com/minecolonies/coremod/util/WorkerUtil.java
Labels: PR: Merge on Monday-Wednesday, PR: Not Ready, PR: Ready for Review

#7338 Improve nearby guard interactions
  src/api/java/com/minecolonies/api/tileentities/AbstractTileEntityColonyBuilding.java
  src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java
  src/main/java/com/minecolonies/coremod/colony/CitizenData.java
  src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java
  src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
Labels: PR: Hotfix, PR: Ready for Review
