Repository ldtteam/minecolonies, pull requests merged in 2024-09, with the labels that each got.

#10178 Fix pepper hummus
  src/datagen/generated/minecolonies/data/minecolonies/compatibility/itemnbtmatching.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/flatbread.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/lembas_scone.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/manchet.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/manchet_dough.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/muffin.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/baker/muffin_dough.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/butter.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/cabochis.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/cheddar_cheese.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/congee.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/cooked_rice.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/eggplant_dolma.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/feta_cheese.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/hand_pie.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/lamb_stew.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/pasta_plain.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/pasta_tomato.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/pepper_hummus.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/pita_hummus.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/pottage.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/raw_noodle.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/rice_ball.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/soy_milk.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/stew_trencher.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/stuffed_pepper.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/stuffed_pita.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/sushi_roll.json
  src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/chef/tofu.json
  src/main/java/com/minecolonies/api/creativetab/ModCreativeTabs.java
  src/main/java/com/minecolonies/api/util/constant/TranslationConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModItemsInitializer.java
  src/main/java/com/minecolonies/core/generation/defaults/workers/DefaultBakerCraftingProvider.java
  src/main/java/com/minecolonies/core/generation/defaults/workers/DefaultChefCraftingProvider.java
  src/main/java/com/minecolonies/core/items/ItemBowlFood.java
  src/main/java/com/minecolonies/core/items/ItemFood.java
Labels: 1.20

#10175 Make pond actually check for what is on wiki
  src/main/java/com/minecolonies/api/util/Pond.java
  src/main/java/com/minecolonies/core/entity/ai/workers/production/agriculture/EntityAIWorkFisherman.java
  src/main/java/com/minecolonies/core/entity/pathfinding/pathjobs/PathJobFindWater.java
  src/main/java/com/minecolonies/core/entity/pathfinding/pathresults/WaterPathResult.java
Labels: Pre-release, 1.21

#10197 Fix time based happiness working as expected [1.21]
  src/main/java/com/minecolonies/api/entity/citizen/citizenhandlers/ICitizenHappinessHandler.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/AbstractHappinessModifier.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/HappinessRegistry.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/IHappinessModifier.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/StaticHappinessModifier.java
  src/main/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java
  src/main/java/com/minecolonies/api/util/constant/NbtTagConstants.java
  src/main/java/com/minecolonies/apiimp/initializer/ModHappinessFactorTypeInitializer.java
  src/main/java/com/minecolonies/core/colony/CitizenData.java
  src/main/java/com/minecolonies/core/colony/CitizenDataView.java
  src/main/java/com/minecolonies/core/entity/citizen/citizenhandlers/CitizenHappinessHandler.java
Labels: 1.21
